Use inventory OS information instead of parameters it in the HostManager methods
wazuh/qa-system-framework pull request #40
Opened 2023-05-31 12:35 UTC by pro-akim

|Related issue|
|-------------|
| #38      |

## Description

This PR aims to add change HostManager methods using Os information from inventory.yml instead of paraters.

### Updated
#### Methods that have changes in the parameterization of Os and/or become:

- check_connection()
- copy_file()
- truncate_file()
- remove_file()
- create_file()
- control_service()
- run_command()
- run_shell()
- find_files()
- get_file_stats()

#### Methods that have changes in the parameterization of become:
- get_file_content()
- modify_file_content()
- synchronize_linux_directory()

## Testing performed

| Tester             | Test path | Jenkins | Local  | OS | Commit | Notes                |
|--------------------|-----------|---------|--------|-----|--------|----------------------|
|  @pro-akim (Developer)  |         |  | [:green_circle:](https://github.com/wazuh/qa-system-framework/files/11654450/report.zip) | Windows - Agent  | https://github.com/wazuh/qa-system-framework/pull/40/commits/9a4eb261691f5db512fd43b589d3fc44e8564959 | |

2023-06-02 09:45 UTC, Rebits requested changes
Great job, but it is necessary to include some logic to handle the become parameter. I suggest setting the become parameter as None by default. If the value is not included when calling the function, we can then determine the become value based on the Host Manager inventory.

2023-06-02 11:28 UTC, pro-akim commented
All methods have been reviewed, and those that receive the 'become' parameter have been configured to default to None.
In the case that a value is provided, that value will be taken as the parameter.
If no value is provided, the method will fetch that value from the inventory using the method get_host_variables(host), taking the value with the index ['become']. If the value is null or None, it will be set to the default value of False.

2023-06-05 10:36 UTC, Rebits requested changes

2023-06-05 10:36 UTC, Rebits commented on src/wazuh_qa_framework/system/host_manager.py
> +                    become = False
```suggestion
become = self.get_host_variables(host).get('become', False) if become is None else become
```

2023-06-05 10:36 UTC, Rebits commented on src/wazuh_qa_framework/system/host_manager.py
> +        if become is None:
Same

2023-06-05 10:36 UTC, Rebits commented on src/wazuh_qa_framework/system/host_manager.py
> +            it will default to False.
Same

2023-06-05 10:36 UTC, Rebits commented on src/wazuh_qa_framework/system/host_manager.py
> +            it will default to False.
Same

2023-06-05 10:36 UTC, Rebits commented on src/wazuh_qa_framework/system/host_manager.py
> +                    become = False
Same

2023-06-05 10:36 UTC, Rebits commented on src/wazuh_qa_framework/system/host_manager.py
> +            become (bool): If no value is provided, it will take from the inventory. If there is no value,
Same

2023-06-05 10:36 UTC, Rebits commented on src/wazuh_qa_framework/system/host_manager.py
> +        if become is None:
Same

2023-06-05 10:36 UTC, Rebits commented on src/wazuh_qa_framework/system/host_manager.py
> +            become (bool): If no value is provided, it will take from the inventory. If there is no value,
Same

2023-06-05 10:36 UTC, Rebits commented on src/wazuh_qa_framework/system/host_manager.py
> +        if become is None:
Same

2023-06-05 10:36 UTC, Rebits commented on src/wazuh_qa_framework/system/host_manager.py
> +            become (bool): If no value is provided, it will take from the inventory. If there is no value,
Same

2023-06-05 10:36 UTC, Rebits commented on src/wazuh_qa_framework/system/host_manager.py
> +        if become is None:
Same

2023-06-05 10:36 UTC, Rebits commented on src/wazuh_qa_framework/system/host_manager.py
> +            become (bool): If no value is provided, it will take from the inventory. If there is no value,
Same

2023-06-05 10:36 UTC, Rebits commented on src/wazuh_qa_framework/system/host_manager.py
> +        if become is None:
Same

2023-06-05 10:36 UTC, Rebits commented on src/wazuh_qa_framework/system/host_manager.py
> +            become (bool): If no value is provided, it will take from the inventory. If there is no value,
Same

2023-06-05 10:36 UTC, Rebits commented on src/wazuh_qa_framework/system/host_manager.py
> +        if become is None:
Same

2023-06-05 10:36 UTC, Rebits commented on src/wazuh_qa_framework/system/host_manager.py
> +            become (bool): If no value is provided, it will take from the inventory. If there is no value,
Same

2023-06-05 10:36 UTC, Rebits commented on src/wazuh_qa_framework/system/host_manager.py
> +        if become is None:
Same

2023-06-05 10:36 UTC, Rebits commented on src/wazuh_qa_framework/system/host_manager.py
> +            become (bool): If no value is provided, it will take from the inventory. If there is no value,
Same

2023-06-05 10:36 UTC, Rebits commented on src/wazuh_qa_framework/system/host_manager.py
> +        if become is None:
Same

2023-06-05 10:36 UTC, Rebits commented on src/wazuh_qa_framework/system/host_manager.py
> +            become (bool): If no value is provided, it will take from the inventory. If there is no value,
Same

2023-06-05 10:36 UTC, Rebits commented on src/wazuh_qa_framework/system/host_manager.py
> +        if become is None:
Same

2023-06-05 10:36 UTC, Rebits commented on src/wazuh_qa_framework/system/host_manager.py
> +            become (bool): If no value is provided, it will take from the inventory. If there is no value,
Same

2023-06-05 10:36 UTC, Rebits commented on src/wazuh_qa_framework/system/host_manager.py
> +        if become is None:
Same

2023-06-05 10:36 UTC, Rebits commented on src/wazuh_qa_framework/system/host_manager.py
> +            ansible_command = 'stat'
Refactor into one line

2023-06-05 10:36 UTC, Rebits commented on src/wazuh_qa_framework/system/host_manager.py
> +            become (bool): If no value is provided, it will take from the inventory. If there is no value,
```suggestion
            become (bool): If no value is provided, it will be taken from the inventory. If the inventory does not provide a value, it will default to False. Defaults None

2023-06-05 14:08 UTC, pro-akim commented on src/wazuh_qa_framework/system/host_manager.py
> +            become (bool): If no value is provided, it will take from the inventory. If there is no value,
Changed in https://github.com/wazuh/qa-system-framework/pull/40/commits/23bf01df9520cf48f6b0c35baf6bcdb108c2b559

2023-06-05 14:08 UTC, pro-akim commented on src/wazuh_qa_framework/system/host_manager.py
> +            ansible_command = 'stat'
Changed in https://github.com/wazuh/qa-system-framework/pull/40/commits/23bf01df9520cf48f6b0c35baf6bcdb108c2b559

2023-06-05 14:08 UTC, pro-akim commented on src/wazuh_qa_framework/system/host_manager.py
> +        if become is None:
Changed in https://github.com/wazuh/qa-system-framework/pull/40/commits/23bf01df9520cf48f6b0c35baf6bcdb108c2b559

2023-06-05 14:08 UTC, pro-akim commented on src/wazuh_qa_framework/system/host_manager.py
> +            become (bool): If no value is provided, it will take from the inventory. If there is no value,
Changed in https://github.com/wazuh/qa-system-framework/pull/40/commits/23bf01df9520cf48f6b0c35baf6bcdb108c2b559

2023-06-05 14:08 UTC, pro-akim commented on src/wazuh_qa_framework/system/host_manager.py
> +        if become is None:
Changed in https://github.com/wazuh/qa-system-framework/pull/40/commits/23bf01df9520cf48f6b0c35baf6bcdb108c2b559

2023-06-05 14:08 UTC, pro-akim commented on src/wazuh_qa_framework/system/host_manager.py
> +                    become = False
Changed in https://github.com/wazuh/qa-system-framework/pull/40/commits/23bf01df9520cf48f6b0c35baf6bcdb108c2b559

2023-06-05 14:08 UTC, pro-akim commented on src/wazuh_qa_framework/system/host_manager.py
> +            it will default to False.
Changed in https://github.com/wazuh/qa-system-framework/pull/40/commits/23bf01df9520cf48f6b0c35baf6bcdb108c2b559

2023-06-05 14:08 UTC, pro-akim commented on src/wazuh_qa_framework/system/host_manager.py
> +        if become is None:
Changed in https://github.com/wazuh/qa-system-framework/pull/40/commits/23bf01df9520cf48f6b0c35baf6bcdb108c2b559

2023-06-05 14:08 UTC, pro-akim commented on src/wazuh_qa_framework/system/host_manager.py
> +                    become = False
Changed in https://github.com/wazuh/qa-system-framework/pull/40/commits/23bf01df9520cf48f6b0c35baf6bcdb108c2b559

2023-06-05 14:09 UTC, pro-akim commented on src/wazuh_qa_framework/system/host_manager.py
> +        if become is None:
Changed in https://github.com/wazuh/qa-system-framework/pull/40/commits/23bf01df9520cf48f6b0c35baf6bcdb108c2b559

2023-06-05 14:09 UTC, pro-akim commented on src/wazuh_qa_framework/system/host_manager.py
> +        if become is None:
Changed in https://github.com/wazuh/qa-system-framework/pull/40/commits/23bf01df9520cf48f6b0c35baf6bcdb108c2b559

2023-06-05 14:09 UTC, pro-akim commented on src/wazuh_qa_framework/system/host_manager.py
> +            become (bool): If no value is provided, it will take from the inventory. If there is no value,
Changed in https://github.com/wazuh/qa-system-framework/pull/40/commits/23bf01df9520cf48f6b0c35baf6bcdb108c2b559

2023-06-05 14:09 UTC, pro-akim commented on src/wazuh_qa_framework/system/host_manager.py
> +        if become is None:
Changed in https://github.com/wazuh/qa-system-framework/pull/40/commits/23bf01df9520cf48f6b0c35baf6bcdb108c2b559

2023-06-05 14:09 UTC, pro-akim commented on src/wazuh_qa_framework/system/host_manager.py
> +            become (bool): If no value is provided, it will take from the inventory. If there is no value,
Changed in https://github.com/wazuh/qa-system-framework/pull/40/commits/23bf01df9520cf48f6b0c35baf6bcdb108c2b559

2023-06-05 14:09 UTC, pro-akim commented on src/wazuh_qa_framework/system/host_manager.py
> +        if become is None:
Changed in https://github.com/wazuh/qa-system-framework/pull/40/commits/23bf01df9520cf48f6b0c35baf6bcdb108c2b559

2023-06-05 14:09 UTC, pro-akim commented on src/wazuh_qa_framework/system/host_manager.py
> +            become (bool): If no value is provided, it will take from the inventory. If there is no value,
Changed in https://github.com/wazuh/qa-system-framework/pull/40/commits/23bf01df9520cf48f6b0c35baf6bcdb108c2b559

2023-06-05 14:09 UTC, pro-akim commented on src/wazuh_qa_framework/system/host_manager.py
> +        if become is None:
Changed in https://github.com/wazuh/qa-system-framework/pull/40/commits/23bf01df9520cf48f6b0c35baf6bcdb108c2b559

2023-06-05 14:09 UTC, pro-akim commented on src/wazuh_qa_framework/system/host_manager.py
> +            become (bool): If no value is provided, it will take from the inventory. If there is no value,
Changed in https://github.com/wazuh/qa-system-framework/pull/40/commits/23bf01df9520cf48f6b0c35baf6bcdb108c2b559

2023-06-05 14:09 UTC, pro-akim commented on src/wazuh_qa_framework/system/host_manager.py
> +        if become is None:
Changed in https://github.com/wazuh/qa-system-framework/pull/40/commits/23bf01df9520cf48f6b0c35baf6bcdb108c2b559

2023-06-05 14:09 UTC, pro-akim commented on src/wazuh_qa_framework/system/host_manager.py
> +        if become is None:
Changed in https://github.com/wazuh/qa-system-framework/pull/40/commits/23bf01df9520cf48f6b0c35baf6bcdb108c2b559

2023-06-05 16:01 UTC, pro-akim commented
After Changes in https://github.com/wazuh/qa-system-framework/commit/23bf01df9520cf48f6b0c35baf6bcdb108c2b559, test were performed.
Tests report updated.

2023-06-05 17:00 UTC, Rebits approved these changes

2023-06-05 17:00 UTC, merged