Include Wazuh agent and manager process remote handling methods
wazuh/qa-system-framework pull request #43
Opened 2023-05-31 16:29 UTC by Rebits

| Related Issue | 
| --- |
| #39 |

### Description

This PR includes some methods for handling Wazuh agent and manager processes in the remote hosts.

2023-06-09 13:53 UTC, juliamagan requested changes
GJ, but some changes are required.

In addition:
- Check quotation marks. You can see the defined standard [here](https://github.com/wazuh/wazuh-qa/wiki/Development-guidelines#-and-).
- Do we need to implement a test for this new code like the ones that existed for the old one?

2023-06-09 13:53 UTC, juliamagan commented on src/wazuh_qa_framework/generic_modules/logging/system_logger.py
> +            ValidationError(f"It was expected to receive a list of allowed handlers: f{HANDLERS}")
```suggestion
            raise ValidationError(f"It was expected to receive a list of allowed handlers: f{HANDLERS}")
```

2023-06-09 13:53 UTC, juliamagan commented on src/wazuh_qa_framework/generic_modules/logging/system_logger.py
> +                    ValidationError(f"{handler} not found")
```suggestion
                    raise ValidationError(f"{handler} not found")
```

2023-06-09 13:53 UTC, juliamagan commented on src/wazuh_qa_framework/generic_modules/logging/system_logger.py
> +                    ValidationError(f"{handler} handler is not allowed")
```suggestion
                    raise ValidationError(f"{handler} handler is not allowed")
```

2023-06-09 13:53 UTC, juliamagan commented on src/wazuh_qa_framework/generic_modules/logging/system_logger.py
> +                    ValidationError(f"{handler} handler is not allowed")
Same here about the expected values and the exception.

2023-06-09 13:53 UTC, juliamagan commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +from wazuh_qa_framework.global_variables.daemons import WAZUH_ANGENT_WINDOWS_SERVICE_NAME
```suggestion
from wazuh_qa_framework.generic_modules.logging.base_logger import SystemLogger
from wazuh_qa_framework.global_variables.daemons import WAZUH_ANGENT_WINDOWS_SERVICE_NAME
from wazuh_qa_framework.system.host_manager import HostManager
```

2023-06-09 13:53 UTC, juliamagan commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            ValueError(f'Host {host} is not an agent')
```suggestion
            raise ValueError(f'Host {host} is not an agent')
```

2023-06-09 13:53 UTC, juliamagan commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            agent_restart_tasks = self.pool.map(self.restart_agent, agent_list)
```suggestion
        if parallel:
            self.pool.map(self.restart_agent, agent_list)
```

2023-06-09 13:53 UTC, juliamagan commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            ValueError(f'Host {host} is not a manager')
```suggestion
            raise ValueError(f'Host {host} is not a manager')
```

2023-06-09 13:53 UTC, juliamagan commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            ValueError(f'Host {host} is not an agent')
```suggestion
            raise ValueError(f'Host {host} is not an agent')
```

2023-06-09 13:53 UTC, juliamagan commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            ValueError(f'Host {host} is not a manager')
```suggestion
            raise ValueError(f'Host {host} is not a manager')
```

2023-06-09 13:53 UTC, juliamagan commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +                                                                                              'wazuh-agent'
We could use `is_windows()`

2023-06-09 13:53 UTC, juliamagan commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            ValueError(f'Host {host} is not an agent')
```suggestion
            raise ValueError(f'Host {host} is not an agent')
```

2023-06-09 13:53 UTC, juliamagan commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            manager_restart_tasks = self.pool.map(self.restart_manager, manager_list)
```suggestion
            self.pool.map(self.restart_manager, manager_list)
```

2023-06-09 13:53 UTC, juliamagan commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            ValueError(f'Host {host} is not a manager')
```suggestion
            raise ValueError(f'Host {host} is not a manager')
```

2023-06-09 13:53 UTC, juliamagan commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        self.logger.info(f'Restarting environment')
```suggestion
        self.logger.info('Restarting environment')
```

2023-06-09 13:53 UTC, juliamagan commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        self.logger.info(f'Stopping environment')
```suggestion
        self.logger.info('Stopping environment')
```

2023-06-09 13:53 UTC, juliamagan commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        self.logger.info(f'Starting environment')
```suggestion
        self.logger.info('Starting environment')
```

2023-06-09 13:53 UTC, juliamagan commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        self.logger.info(f'Environment started successfully')
```suggestion
        self.logger.info('Environment started successfully')
```

2023-06-09 13:53 UTC, juliamagan commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        return host in self.get_managers()
We could move these functions to `host_manager.py` like `is_windows()`, `is_linux()`...

2023-06-12 16:53 UTC, Rebits commented on pyproject.toml
> +system_tests_launcher = [
This PR will also close that issue

2023-06-12 16:54 UTC, Rebits commented on src/wazuh_qa_framework/generic_modules/logging/system_logger.py
> +            self.__formatter = FORMATERS['basic']
Refactored system logger. Fix included in base logger 6433e59732ba60c857189063cf636fc39a1ac9bb

2023-06-12 16:54 UTC, Rebits commented on src/wazuh_qa_framework/generic_modules/logging/system_logger.py
> +            ValidationError(f"It was expected to receive a list of allowed handlers: f{HANDLERS}")
Refactored system logger. Fix included in base logger 6433e59732ba60c857189063cf636fc39a1ac9bb

2023-06-12 16:54 UTC, Rebits commented on src/wazuh_qa_framework/generic_modules/logging/system_logger.py
> +                    ValidationError(f"{handler} handler is not allowed")
Refactored system logger. Fix included in base logger 6433e59732ba60c857189063cf636fc39a1ac9bb

2023-06-12 16:54 UTC, Rebits commented on src/wazuh_qa_framework/generic_modules/logging/system_logger.py
> +                    ValidationError(f"{handler} handler is not allowed")
Refactored system logger. Fix included in base logger 6433e59732ba60c857189063cf636fc39a1ac9bb

2023-06-12 16:54 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +from wazuh_qa_framework.global_variables.daemons import WAZUH_ANGENT_WINDOWS_SERVICE_NAME
Done 656f1c027226e5e35aee8c292f8fc1ddfcf3214c

2023-06-12 16:54 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +                                                                                              'wazuh-agent'
Done 656f1c027226e5e35aee8c292f8fc1ddfcf3214c

2023-06-12 16:54 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            agent_restart_tasks = self.pool.map(self.restart_agent, agent_list)
Done 656f1c027226e5e35aee8c292f8fc1ddfcf3214c

2023-06-12 16:55 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            ValueError(f'Host {host} is not a manager')
Done 656f1c027226e5e35aee8c292f8fc1ddfcf3214c

2023-06-12 16:55 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +                                                                                              'wazuh-agent'
Done 656f1c027226e5e35aee8c292f8fc1ddfcf3214c

2023-06-12 16:55 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            ValueError(f'Host {host} is not a manager')
Done 656f1c027226e5e35aee8c292f8fc1ddfcf3214c

2023-06-12 16:55 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +                                                                                              'wazuh-agent'
Done 656f1c027226e5e35aee8c292f8fc1ddfcf3214c

2023-06-12 16:55 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            ValueError(f'Host {host} is not an agent')
Done 656f1c027226e5e35aee8c292f8fc1ddfcf3214c

2023-06-12 16:55 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            manager_restart_tasks = self.pool.map(self.restart_manager, manager_list)
Done 656f1c027226e5e35aee8c292f8fc1ddfcf3214c

2023-06-12 16:55 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            ValueError(f'Host {host} is not a manager')
Done 656f1c027226e5e35aee8c292f8fc1ddfcf3214c

2023-06-12 16:55 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        self.logger.info(f'Restarting environment')
Done 656f1c027226e5e35aee8c292f8fc1ddfcf3214c

2023-06-12 16:56 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        self.logger.info(f'Stopping environment')
Done 656f1c027226e5e35aee8c292f8fc1ddfcf3214c

2023-06-12 17:00 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        return host in self.get_managers()
In my opinion, it would be better to place `is_manager` and `is_agent` within this class since these groups are specifically relevant in a Wazuh Environment. By doing so, the class becomes more self-contained and maintains a clear association with the environment it operates in. On the other hand, `is_windows` and `is_linux` merely pertain to the operating system and can be utilized for various purposes.

2023-06-14 08:55 UTC, juliamagan requested changes

2023-06-14 08:55 UTC, juliamagan commented on tests/generic_modules/test_logging/test_base_logger.py
> +def test_output_color(source, color, message, expected_message, create_destroy_sample_file):
What about `True, True` case?

2023-06-14 10:12 UTC, juliamagan approved these changes
LGTM

2023-06-14 10:16 UTC, merged