Add function to run playbook on a host
wazuh/qa-system-framework pull request #49
Opened 2023-06-06 20:31 UTC by BelenValdivia

2023-06-12 17:05 UTC, Rebits requested changes
Good Job. Some changes are required

2023-06-12 17:05 UTC, Rebits commented on src/wazuh_qa_framework/system/host_manager.py
> +import ansible_runner
It is required to update the project dependencies?

2023-06-12 17:05 UTC, Rebits commented on src/wazuh_qa_framework/system/host_manager.py
> +            path (str): The full path of the file/object to get the facts of.
```suggestion
            playbook_path (str): The full path of the file/object to get the facts of.
```

2023-06-12 17:05 UTC, Rebits commented on src/wazuh_qa_framework/system/host_manager.py
> +        return runner.rc == 0
Is necessary this return?

2023-06-12 18:40 UTC, BelenValdivia commented on src/wazuh_qa_framework/system/host_manager.py
> +        return runner.rc == 0
I think it's ok to know if the playbook runs successfully. Why do you think it's not necessary?

2023-06-21 13:21 UTC, Rebits requested changes

2023-06-21 13:21 UTC, Rebits commented on src/wazuh_qa_framework/system/host_manager.py
> +import ansible_runner
In the `pyproject.toml` for the `system_tests_launcher` optional dependency

2023-06-21 13:21 UTC, Rebits commented on src/wazuh_qa_framework/system/host_manager.py
> +        return runner.rc == 0
Because if it fails it should raise an Exception, so the return statement does not provide extra information.
IMHO is better to return the runner object instead to gather stdout, stderr, events, etc

2023-06-21 19:51 UTC, BelenValdivia commented
- Added ansible-runner as a dependency in `project.toml`
![image](https://github.com/wazuh/qa-system-framework/assets/26927338/e623ac72-30ba-4f61-9e96-a6176aa6536b)

2023-06-21 20:03 UTC, BelenValdivia commented on src/wazuh_qa_framework/system/host_manager.py
> +        return runner.rc == 0
Done 20f7457ab10f4e94d38862d944ed019fe74da734

2023-06-21 20:04 UTC, BelenValdivia commented on src/wazuh_qa_framework/system/host_manager.py
> +        return runner.rc == 0
Done 20f7457ab10f4e94d38862d944ed019fe74da734

2023-06-21 20:04 UTC, BelenValdivia commented on src/wazuh_qa_framework/system/host_manager.py
> +import ansible_runner
Done bbfb5720fca78d14cad23c3767fae1a33c43a982

2023-06-23 12:55 UTC, Rebits approved these changes
LGTM

2023-06-23 12:56 UTC, merged