Add configuration methods
wazuh/qa-system-framework pull request #56
Opened 2023-06-14 14:25 UTC by juliamagan

## Description

2023-06-28 11:29 UTC, Rebits requested changes
GJ! Some minor changes are required

2023-06-28 11:29 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +}
These vars should be moved into a common variables module

2023-06-28 11:29 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +
We should move all these functions to the configuration module.
Functions to get the directory path should be moved to a separate module too.

2023-06-28 11:29 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +    def configure_host(self, host, configuration_file, configuration_values):
Update the examples in the docstring

2023-06-28 11:29 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        if configuration_file == 'ossec.conf' or configuration_file == 'agent.conf':
```suggestion
        if configuration_file in ['ossec.conf', 'agent.conf']:
```
We can also move that list into a variable called xml_configuration_files

2023-07-05 15:21 UTC, juliamagan commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +}
As the development can be long and goes out of the scope of this PR, the following issue has been created and will be worked on:

https://github.com/wazuh/qa-system-framework/issues/74

2023-07-06 09:53 UTC, juliamagan commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +
Done in ecc6d4c

2023-07-06 09:53 UTC, juliamagan commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +    def configure_host(self, host, configuration_file, configuration_values):
Done in 8aa3f89

2023-07-06 09:54 UTC, juliamagan commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        if configuration_file == 'ossec.conf' or configuration_file == 'agent.conf':
Done in 1deaf31

2023-07-07 19:19 UTC, BelenValdivia requested changes

2023-07-07 19:19 UTC, BelenValdivia commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        backup_file = os.path.join(temporal_folder, file + '.backup',)
There is an extra comma at the end of the `backup_file` definition

2023-07-07 19:19 UTC, BelenValdivia commented on src/wazuh_qa_framework/system/wazuh_handler.py
>              backup_configuration (dict): Backup configuration filepaths
Argument name `backup_configurations (dict):`...

2023-07-20 13:12 UTC, juliamagan commented on src/wazuh_qa_framework/system/wazuh_handler.py
>              backup_configuration (dict): Backup configuration filepaths
Done in 49f9322

2023-07-20 13:13 UTC, juliamagan commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        backup_file = os.path.join(temporal_folder, file + '.backup',)
Done in 49f9322

2023-07-20 13:13 UTC, juliamagan commented on src/wazuh_qa_framework/system/wazuh_handler.py
>              configuration_list (dict): Host configuration files to backup
Done in 49f9322

2023-07-25 12:52 UTC, QU3B1M commented on src/wazuh_qa_framework/generic_modules/tools/configuration.py
> +    def to_elementTree(str_list: List[str], root_delimeter: str = "</ossec_config>") -> ET.ElementTree:
This function's name is in a mix of snake case and camel case. It is recommended to use only snake case in Python.
```suggestion
    def to_element_tree(str_list: List[str], root_delimeter: str = "</ossec_config>") -> ET.ElementTree:
```

2023-08-01 08:51 UTC, juliamagan commented on src/wazuh_qa_framework/generic_modules/tools/configuration.py
> +    def to_elementTree(str_list: List[str], root_delimeter: str = "</ossec_config>") -> ET.ElementTree:
Done in 72828b5

2023-08-02 13:00 UTC, QU3B1M commented
LGTM! 🚀

2023-08-02 19:14 UTC, BelenValdivia commented
LGTM!

2023-08-02 19:14 UTC, BelenValdivia approved these changes

2023-09-06 07:14 UTC, merged