Add a monitoring class to the regex monitoring tool
wazuh/qa-system-framework pull request #58
Opened 2023-06-14 15:49 UTC by roronoasins

## Description

This PR adds a class that helps us to handle the data that `FileRegexMonitor` uses, such as patterns, callbacks, etc.

### Add

- Add `MonitoringObject` class
- Add custom pattern to `meta_testing/utils.py`

### Change

- Adapt `FileRegexMonitor` to use the new monitoring class
- Adapt `generic_modules/test_tools/test_file_regex_monitor/test_accumulations.py` with the new changes
- Adapt `generic_modules/test_tools/test_file_regex_monitor/test_callback.py` with the new changes
- Adapt `generic_modules/test_tools/test_file_regex_monitor/test_callback_result.py ` with the new changes
- Adapt `generic_modules/test_tools/test_file_regex_monitor/test_file_encoding.py` with the new changes
- Adapt `generic_modules/test_tools/test_file_regex_monitor/test_only_new_events.py` with the new changes

# Checks

<details><summary>pep8</summary>

> alias pep8="pycodestyle --max-line-length=120 --show-source --show-pep8"

```
pc:~/wazuh/system-framework/qa-system-framework$ pep8 src/wazuh_qa_framework/generic_modules/tools/file_regex_monitor.py 
pc:~/wazuh/system-framework/qa-system-framework$ pep8 tests/generic_modules/
pc:~/wazuh/system-framework/qa-system-framework$
```

</details>

<details><summary><code>MonitoringObject</code> string representation</summary>

<details><summary>Custom script</summary>

```py
from wazuh_qa_framework.generic_modules.tools.file_regex_monitor import MonitoringObject, FileRegexMonitor
from wazuh_qa_framework.generic_modules.threading.thread import Thread

patterns = {
    r'ossec.*': 'Check if ossec appears',
    r'wazuh.*': 'Check if wazuh appears',
    r'wazuh-modulesd:syscollector: INFO: Module started.': 'Check if syscollector scan has been started.',
    r'wazuh-modulesd:syscollector: INFO: Evaluation finished.': 'Checks if the syscollector scan has been completed.',
    r'Starting evaluation of policy: \'(.*)\'\n': 'Catch the policy file when it is evaluated.',
    r'DEBUG: Module disabled. Exiting...': 'Check vd debug'
}

log_file = '/var/ossec/logs/ossec.log'
timeout = 1

for pattern, description in patterns.items():

    # with description
    # monitoring = MonitoringObject(description=description, pattern='testing.*', timeout=timeout, monitored_file=log_file)
    # without description
    monitoring = MonitoringObject(pattern=pattern, timeout=timeout, monitored_file=log_file)

    print(f"monitoring instance: {monitoring.__str__()}")

    # Start the file regex monitoring
    file_regex_monitor_parameters = {'monitoring': monitoring}
    file_regex_monitor_process = Thread(target=FileRegexMonitor, parameters=file_regex_monitor_parameters)

    file_regex_monitor_process.start()

    file_regex_monitor_process.join()

```

</details>

Test
```
root@manager44:/media/sf_qa-system-framework/tests# python3 test.py 
monitoring instance: MonitoringObject-.*ossec.*-/var/ossec/logs/ossec.log
monitoring instance: MonitoringObject-.*wazuh.*-/var/ossec/logs/ossec.log
monitoring instance: MonitoringObject-.*wazuh-modulesd:syscollector: INFO: Module started.-/var/ossec/logs/ossec.log
monitoring instance: MonitoringObject-.*wazuh-modulesd:syscollector: INFO: Evaluation finished.-/var/ossec/logs/ossec.log
monitoring instance: MonitoringObject-.*Starting evaluation of policy: \'(.*)\'\n-/var/ossec/logs/ossec.log
monitoring instance: MonitoringObject-.*DEBUG: Module disabled. Exiting...-/var/ossec/logs/ossec.log
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/wazuh_qa_framework-1.0.0-py3.10.egg/wazuh_qa_framework/generic_modules/tools/file_regex_monitor.py", line 206, in __start
    raise TimeoutError(f"Events from {self.monitoring.monitored_file} did not match with the callback" +
wazuh_qa_framework.generic_modules.exceptions.exceptions.TimeoutError: Events from /var/ossec/logs/ossec.log did not match with the callback from MonitoringObject-.*DEBUG: Module disabled. Exiting...-/var/ossec/logs/ossec.log
root@manager44:/media/sf_qa-system-framework/tests#
```

</details>

2023-07-03 23:18 UTC, BelenValdivia requested changes

2023-07-03 23:18 UTC, BelenValdivia commented on src/wazuh_qa_framework/generic_modules/tools/file_regex_monitor.py
> +        if callback:
You can simplify these two if in one:
```suggestion
        if callback and not callable(callback):
```

2023-07-04 09:51 UTC, pro-akim commented on src/wazuh_qa_framework/generic_modules/tools/file_regex_monitor.py
It should be: beginning

2023-07-04 12:24 UTC, pro-akim requested changes

2023-07-04 12:24 UTC, pro-akim commented on src/wazuh_qa_framework/generic_modules/tools/file_regex_monitor.py
Not related with new changes, but in line 5:
"beginning" spelling should be fixed.

2023-07-19 16:17 UTC, roronoasins commented on src/wazuh_qa_framework/generic_modules/tools/file_regex_monitor.py
> +        if callback:
Done https://github.com/wazuh/qa-system-framework/pull/58/commits/c8eae8375bb869545bb6daaa3650e4080c3bb741

2023-07-31 12:40 UTC, BelenValdivia commented
LGTM!

2023-07-31 12:40 UTC, BelenValdivia approved these changes

2023-09-06 08:00 UTC, merged