Add common API calls
wazuh/qa-system-framework pull request #70
Opened 2023-06-26 14:54 UTC by juliamagan

## Description

In this PR we have added all the endpoints that were previously used in the system tests, and some new ones that may be useful.

`WazuhHandler` will have a `WazuhAPI` object as an attribute, and will be able to call requests when necessary.

2023-06-28 11:07 UTC, Rebits requested changes
Great job! Some changes are required

2023-06-28 11:07 UTC, Rebits commented on src/wazuh_qa_framework/wazuh_components/api/wazuh_api.py
> +                return agent['id']
Should we raise an exception in case the agent is not registered?

2023-07-06 10:29 UTC, juliamagan commented on src/wazuh_qa_framework/wazuh_components/api/wazuh_api.py
> +                return agent['id']
Done in a0c5f44

2023-08-03 09:38 UTC, Rebits requested changes
Great job! Some changes are required

2023-08-03 09:38 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +    def get_agents_id(self, host):
```suggestion
    def get_agent_id(self, host):
```

2023-08-03 09:38 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +    def restart_agent(self, host, method='service'):
method param should be included in `restarts_agents` too

2023-08-03 11:32 UTC, juliamagan commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +    def restart_agent(self, host, method='service'):
Done in ae31c81

2023-10-03 06:32 UTC, merged