Group Assign and unassign methods
wazuh/qa-system-framework pull request #71
Opened 2023-06-28 08:46 UTC by pro-akim

| Related Issue | 
| --- |
| #60  |

### Description

This PR includes methods for assign, unassign, create and remove groups as check existence of agent in a group.

### Evidences

Running:
<details>
1. wh.create_group("test1_group")
2. wh.assign_agent_group("002", "test1_group", method='cmd')
3. wh.assign_agent_group("001", "test1_group", method='api')
4. wh.assign_agents_group(agent, 'test3_group', method='cmd')
5. wh.assign_agents_group(agent, 'test3_group', method='api')
6. wh.check_agent_groups("002", "test3_group", ['manager1'])
7. wh.unassign_agent_group('001', 'test4_group', method='api')
</details>

Results:
<details>
1. group created
2. agent 002 assigned to test1_group
3. agent 001 assigned to test1_group
4. agent 001 and 002 assigned to test3_group
5. agent 001 and 002 assigned to test3_group
6. agent 002 checked in group test3_group
7. agent 001 unassigned from test4_group
</details>

2023-07-03 15:31 UTC, roronoasins commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        self.run_command('manager1', f"/var/ossec/bin/agent_groups -q -a -g {group_name}", become=True)
I would add the manager as a parameter

```suggestion
    def create_group(self, manager, group_name):
        """Function to create a group.
        Args:
            group_name (str): Name of the group.
        """
        self.logger.info(f'creating new {manager} group: {group_name}')
        self.run_command(manager, f"/var/ossec/bin/agent_groups -q -a -g {group_name}", become=True)
```

2023-07-03 15:35 UTC, roronoasins commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +    def create_group(self, group_name):
We should also have the [API method](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.agent_controller.post_group)

```suggestion
    def create_group(self, group_name, method):
```

2023-07-03 15:38 UTC, roronoasins commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        self.run_command('manager1', f"/var/ossec/bin/agent_groups -q -a -g {group_name}", become=True)
I would define `/var/ossec/bin/agent_groups` within the framework as `AGENTS_GROUP_BIN` or any name that represent the binary. We can discuss if the `system/__init__.py` is the right place or which one

```suggestion
        self.run_command('manager1', f"{AGENTS_GROUP_BIN} -q -a -g {group_name}", become=True)
```

2023-07-03 15:39 UTC, roronoasins commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        self.logger.info(f'creating group {group_name}')
```suggestion
        self.logger.info(f"creating group {group_name}")
```

2023-07-03 15:48 UTC, roronoasins commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +                endpoint = f'/agents/{agent}/group/{id_group}'
Is possible to add a method that retrieves the endpoint, so we can reuse that piece of code? I don't know if we can do that by obtaining the endpoint based on the information we provide to that new method.

2023-07-20 12:26 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        self.run_command('manager1', f"/var/ossec/bin/agent_groups -q -a -g {group_name}", become=True)
It was created a method that return the path (based in the rest of path managing)

2023-07-20 12:52 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +                endpoint = f'/agents/{agent}/group/{id_group}'
It is possible to do so, however, I will leave it without changes in order to discuss it in the near future.

2023-07-21 11:00 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        self.run_command('manager1', f"/var/ossec/bin/agent_groups -q -a -g {group_name}", become=True)
Done in https://github.com/wazuh/qa-system-framework/pull/71/commits/6e4fa8a41bfb8248e339d6eb0911ce229ca57084

2023-07-21 11:01 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +    def create_group(self, group_name):
Done in https://github.com/wazuh/qa-system-framework/pull/71/commits/6e4fa8a41bfb8248e339d6eb0911ce229ca57084

2023-07-21 11:01 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        self.run_command('manager1', f"/var/ossec/bin/agent_groups -q -a -g {group_name}", become=True)
Done in https://github.com/wazuh/qa-system-framework/pull/71/commits/6e4fa8a41bfb8248e339d6eb0911ce229ca57084

2023-07-21 11:04 UTC, pro-akim commented
# Update
Some fixes were done.
It will be important to have some communication with the team in order to define if validations are required

These are some Tests performed
<details>

- root@ip-172-31-15-43:/home/qa# /var/ossec/bin/agent_groups -l

Groups (1):
  default (2)
Unassigned agents: 0.



- wh.assign_agent_group('manager1', '001', 'group1', method='api')

root@ip-172-31-15-43:/home/qa# /var/ossec/bin/agent_groups -l
Groups (2):
  default (2)
  group1 (1)
Unassigned agents: 0.


- wh.assign_agent_group('manager1', '002', 'group1', method='cmd')

root@ip-172-31-15-43:/home/qa# /var/ossec/bin/agent_groups -l
Groups (2):
  default (2)
  group1 (2)
Unassigned agents: 0.

- wh.unassign_agent_group('manager1', '002', 'group1')

root@ip-172-31-15-43:/home/qa# /var/ossec/bin/agent_groups -l
Groups (2):
  default (2)
  group1 (1)
Unassigned agents: 0.

- wh.assign_agents_group('manager1', ['001','002'], 'group1', method='cmd')
root@ip-172-31-15-43:/home/qa# /var/ossec/bin/agent_groups -l
Groups (2):
  default (2)
  group1 (2)
Unassigned agents: 0.

- wh.unassign_agents_group('manager1', ['001','002'], 'group1')
root@ip-172-31-15-43:/home/qa# /var/ossec/bin/agent_groups -l
Groups (2):
  default (2)
  group1 (0)
Unassigned agents: 0.

- wh.assign_agents_group('manager1', ['001','002'], 'group1', method='api')

root@ip-172-31-15-43:/home/qa# /var/ossec/bin/agent_groups -l
Groups (2):
  default (2)
  group1 (2)
Unassigned agents: 0.

- wh.check_agent_groups('001', 'group1', ['manager1'])
None
</details>

2023-07-24 13:39 UTC, pro-akim commented
# Update
After a conversation with the team about adding features to check the previous existence of groups or assigned agents, a new parameter was added in each method in order to check or not previous existences.

2023-07-25 19:05 UTC, Deblintrake09 commented
LGTM!

<details><summary>Testing results</summary>

1. Create a group through CMD: wh.create_group('manager1', 'group2', method='cmd') :green_circle: 
```
# /var/ossec/bin/agent_groups
Groups (2):
  default (2)
  group1 (0)
```

2. Create a group through API: wh.create_group('manager1', 'group2', method='api') :green_circle: 
```
# /var/ossec/bin/agent_groups
Groups (3):
  default (2)
  group1 (0)
  group2 (0)
```

3. Assign agent to group through CMD:  wh.assign_agent_group("manager1","002", "group1", method='cmd') :green_circle: 
```
# /var/ossec/bin/agent_groups -i 002
Groups (2):
  default (2)
  group1 (1)
  group2 (0)
Unassigned agents: 0.
```

4. Assign agent to group through API:  wh.assign_agent_group("manager1", "001", "group1", method='api') :green_circle: 
```
# /var/ossec/bin/agent_groups -i 001
Groups (2):
  default (2)
  group1 (1)
  group2 (0)
Unassigned agents: 0.
```

5. Assign multiple agents to non existing group -  Command: wh.assign_agents_group("manager1", agent, 'group3', method='"api') - Group not created and agents not assigned. :yellow_circle: 
```
$ python3 test2.py 
2023-07-25 15:39:09,666 - INFO - Assigning agent 001 from group group3 from manager1 using CMD [WazuhEnvironmentHandler assign_agents_group:950]
2023-07-25 15:39:09,667 - INFO - Checking agent 001 in group group3 [WazuhEnvironmentHandler check_agent_group:870]
2023-07-25 15:39:19,213 - INFO - Assign agent 001 to group group3 using API [WazuhEnvironmentHandler assign_agent_group:935]
2023-07-25 15:39:21,395 - INFO - Assigning agent 002 from group group3 from manager1 using CMD [WazuhEnvironmentHandler assign_agents_group:950]
2023-07-25 15:39:21,396 - INFO - Checking agent 002 in group group3 [WazuhEnvironmentHandler check_agent_group:870]
2023-07-25 15:39:28,525 - INFO - Assign agent 002 to group group3 using API [WazuhEnvironmentHandler assign_agent_group:935]
None

# /var/ossec/bin/agent_groups -i 001
Groups (3):
  default (2)
  group1 (1)
  group2 (0)
Unassigned agents: 0.
```

6. Add multiple agents to group:  wh.assign_agents_group("manager1", agent, 'group2', method='api') :green_circle: 
```
# /var/ossec/bin/agent_groups -i 001
Groups (3):
  default (2)
  group1 (1)
  group2 (2)
Unassigned agents: 0.
# /var/ossec/bin/agent_groups -i 002
Groups (3):
  default (2)
  group1 (1)
  group2 (2)
Unassigned agents: 0.
```

7. Check agent is in group: wh.check_agent_group("manager1", "002", "group1") :green_circle: 
```
$ python3 test2.py 
2023-07-25 15:57:08,655 - INFO - Checking agent 002 in group group1 [WazuhEnvironmentHandler check_agent_group:870]
False
```
8. Remove agent from group: wh.unassign_agent_group("manager1, '001', 'group1') :green_circle: 
```
a# /var/ossec/bin/agent_groups -i 001
Groups (2):
  default (2)
  group1 (0)
  group2 (2)
Unassigned agents: 0.
```
</details>

9. Delete a group using API: wh.delete_group('manager1', 'group1', method='api', check_previous=False) :green_circle: 
```
# /var/ossec/bin/agent_groups
Groups (2):
  default (2)
  group2 (2)
```
10. Delete a group using Folder method: wh.delete_group('manager1', 'group1', method='folder', check_previous=False) :green_circle: 
```
# /var/ossec/bin/agent_groups
Groups (1):
  default (2)
```

2023-07-25 19:16 UTC, Deblintrake09 approved these changes
LGTM!

<details><summary>Testing results :green_circle: </summary>

1. Create a group through CMD: wh.create_group('manager1', 'group2', method='cmd') :green_circle: 
```
# /var/ossec/bin/agent_groups
Groups (2):
  default (2)
  group1 (0)
```

2. Create a group through API: wh.create_group('manager1', 'group2', method='api') :green_circle: 
```
# /var/ossec/bin/agent_groups
Groups (3):
  default (2)
  group1 (0)
  group2 (0)
```

3. Assign agent to group through CMD:  wh.assign_agent_group("manager1","002", "group1", method='cmd') :green_circle: 
```
# /var/ossec/bin/agent_groups -i 002
Groups (2):
  default (2)
  group1 (1)
  group2 (0)
Unassigned agents: 0.
```

4. Assign agent to group through API:  wh.assign_agent_group("manager1", "001", "group1", method='api') :green_circle: 
```
# /var/ossec/bin/agent_groups -i 001
Groups (2):
  default (2)
  group1 (1)
  group2 (0)
Unassigned agents: 0.
```

5. Add multiple agents to group:  wh.assign_agents_group("manager1", agent, 'group2', method='api') :green_circle: 
```
# /var/ossec/bin/agent_groups -i 001
Groups (3):
  default (2)
  group1 (1)
  group2 (2)
Unassigned agents: 0.
# /var/ossec/bin/agent_groups -i 002
Groups (3):
  default (2)
  group1 (1)
  group2 (2)
Unassigned agents: 0.
```

6. Check agent is in group: wh.check_agent_group("manager1", "002", "group1") :green_circle: 
```
$ python3 test2.py 
2023-07-25 15:57:08,655 - INFO - Checking agent 002 in group group1 [WazuhEnvironmentHandler check_agent_group:870]
False
```
7. Remove agent from group: wh.unassign_agent_group("manager1, '001', 'group1') :green_circle: 
```
a# /var/ossec/bin/agent_groups -i 001
Groups (2):
  default (2)
  group1 (0)
  group2 (2)
Unassigned agents: 0.
```
8. Delete a group using API: wh.delete_group('manager1', 'group1', method='api', check_previous=False) :green_circle: 
```
# /var/ossec/bin/agent_groups
Groups (2):
  default (2)
  group2 (2)
```
9. Delete a group using Folder method: wh.delete_group('manager1', 'group1', method='folder', check_previous=False) :green_circle: 
```
# /var/ossec/bin/agent_groups
Groups (1):
  default (2)
```
</details>

It's important to note that this will not work until the pipeline's permissions are changed.

2023-07-27 08:45 UTC, roronoasins commented
LGTM

2023-07-27 08:47 UTC, roronoasins approved these changes
LGTM

2023-07-27 16:11 UTC, Rebits requested changes
GJ! Some changes are required

2023-07-27 16:11 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +    def unassign_agent_group(self, manager, id_agent, group_name, check_previous=True):
Why this method does not allow multiple options to unassign an agent group?

2023-07-27 16:11 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            self.unassign_agent_group(manager, agent, group_name, check_previous=check_previous)
Please, make some changes to allow run this parallel

2023-07-27 16:11 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +    def unassign_agents_group(self, manager, list_id_agent, group_name, check_previous=True):
Same as before, change list of agent's ids with agent's names

2023-07-27 16:11 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +    def unassign_agents_group(self, manager, list_id_agent, group_name, check_previous=True):
```suggestion
    def unassign_agents_group(self, manager, list_id_agent, group_name, check_group=True):
```

2023-07-27 16:11 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            self.unassign_agent_group(manager, agent, group_name, check_previous=check_previous)
```suggestion
            self.unassign_agent_group(manager, agent, group_name, check_group=check_group)
```

2023-07-27 16:11 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            check_previous (str): Check if the agents are already assigned to the group.
```suggestion
            check_group (str): Check if the agents are already assigned to the group.
```

2023-07-27 16:11 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            check_previous (str): Check if the agent is already assigned to the group.
```suggestion
            check_group (str): Check if the agent is already assigned to the group.
```

2023-08-22 14:11 UTC, pro-akim commented
## Update

Changes after review done.

It has to be created 
- get_agent_id
- get agent_name_from_ip
- get_agents_id
- get_group_list
- get_agent_names_in_group
- check_group
- check_agent_group

Additionally, parallel, check_group functions added and checked.

<details><summary>Testing</summary>
wh.get_agent_id('agent1')
001

wh.get_agent_name_from_ip('172.31.9.65')
agent1

wh.get_agents_id(['agent1','agent2'])
['001', '002']

wh.get_group_list('manager1', method='api')
['default', 'grupo1', 'grupo2']

wh.get_group_list('manager1', method='cmd')
['default', 'grupo1', 'grupo2']

wh.get_agents_names_in_group('manager1', 'grupo1')
['agent1', 'agent2']


wh.check_group('manager1', 'grupo1', method='api')
True

wh.check_group('manager1', 'grupo1', method='cmd')
True

wh.check_agent_group('manager1', 'agent1', 'grupo1')
True

wh.check_agent_group('manager1', 'agent1', 'grupo10')
False

wh.create_group('manager1', 'grupotest1', method='api', check_group=True)
wh.check_group('manager1', 'grupotest1')
True

wh.create_group('manager1', 'grupotest1', method='api', check_group=True)
2023-08-22 15:51:13,647 - INFO - grupotest1 already exists [WazuhEnvironmentHandler create_group:968]
wh.check_group('manager1', 'grupotest1')
True

wh.create_group('manager1', 'grupotest1', method='api', check_group=False)
wh.check_group('manager1', 'grupotest1')
True

wh.create_group('manager1', 'grupotest2', method='api', check_group=True)
wh.check_group('manager1', 'grupotest2')
True

wh.delete_group('manager1', 'grupotest2', method='cmd', check_group=True)
wh.check_group('manager1', 'grupotest2')
False

wh.delete_group('manager1', 'grupotest2', method='cmd', check_group=True)
2023-08-22 15:55:16,587 - INFO - grupotest2 does not exists [WazuhEnvironmentHandler delete_group:987]
wh.check_group('manager1', 'grupotest2')
False

wh.delete_group('manager1', 'grupotest3', method='folder', check_group=True)
wh.check_group('manager1', 'grupotest3')
False

wh.delete_group('manager1', 'grupotest3', method='folder', check_group=True)
2023-08-22 15:56:46,886 - INFO - grupotest3 does not exists [WazuhEnvironmentHandler delete_group:987]
wh.check_group('manager1', 'grupotest3')
False

wh.assign_agent_group('manager1', 'agent1', group_name='default', check_group=True)
wh.check_agent_group('manager1', 'agent1', 'default')
True

wh.assign_agent_group('manager1', 'agent1', group_name='default', check_group=True)
wh.check_agent_group('manager1', 'agent1', 'default')
True

wh.assign_agent_group('manager1', 'agent1', group_name='default', check_group=True)
2023-08-22 15:58:54,915 - INFO - agent1 is already assigned to default [WazuhEnvironmentHandler assign_agent_group:1013]
wh.check_agent_group('manager1', 'agent1', 'default')
True

wh.assign_agents_group('manager1', ['agent1', 'agent2'], group_name='grupotest1', method='api', check_group=True)
wh.check_agent_group('manager1', 'agent1', 'grupotest1')
wh.check_agent_group('manager1', 'agent2', 'grupotest1')
True
True

wh.assign_agents_group('manager1', ['agent1', 'agent2'], group_name='grupotest1', method='api', check_group=True)
wh.check_agent_group('manager1', 'agent1', 'grupotest1')
wh.check_agent_group('manager1', 'agent2', 'grupotest1')
2023-08-22 16:01:47,126 - INFO - agent2 is already assigned to grupotest1 [WazuhEnvironmentHandler assign_agent_group:999]
2023-08-22 16:01:47,128 - INFO - agent1 is already assigned to grupotest1 [WazuhEnvironmentHandler assign_agent_group:999]
True
True

wh.unassign_agent_group('manager1', 'agent1', group_name='default', check_group=True)
wh.check_agent_group('manager1', 'agent1', 'default')
False

wh.unassign_agents_group('manager1', ['agent1', 'agent2'], group_name='grupotest1', check_group=True)  
wh.check_agent_group('manager1', 'agent1', 'grupotest1')
wh.check_agent_group('manager1', 'agent2', 'grupotest1')
2023-08-22 16:04:20,490 - INFO - Removing agent agent2 from group grupotest1 using API [WazuhEnvironmentHandler unassign_agent_group:1039]
2023-08-22 16:04:20,490 - INFO - Removing agent agent1 from group grupotest1 using API [WazuhEnvironmentHandler unassign_agent_group:1039]
False
False

wh.assign_agents_group('manager1', ['agent1', 'agent2'], group_name='grupotest2', method='api', check_group=True, parallel=False)
wh.check_agent_group('manager1', 'agent1', 'grupotest1')
wh.check_agent_group('manager1', 'agent2', 'grupotest1')
True
True

wh.unassign_agents_group('manager1', ['agent1', 'agent2'], group_name='grupotest1', check_group=True, parallel=False)  
wh.check_agent_group('manager1', 'agent1', 'grupotest1')
wh.check_agent_group('manager1', 'agent2', 'grupotest1')
2023-08-22 16:04:20,490 - INFO - Removing agent agent2 from group grupotest1 using API [WazuhEnvironmentHandler unassign_agent_group:1039]
2023-08-22 16:04:20,490 - INFO - Removing agent agent1 from group grupotest1 using API [WazuhEnvironmentHandler unassign_agent_group:1039]
False
False

</details>

2023-08-22 15:13 UTC, pro-akim commented
## Update
Linting is pointing out a line that does not exist: (1088)
The line 1049 does not show a indentation problem as well.
Moved to pending review

2023-08-23 08:28 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            check_previous (str): Check if the agents are already assigned to the group.
Done in https://github.com/wazuh/qa-system-framework/pull/71/commits/115f8bd3795d583a316bdc9c13a895abecdbc845

2023-08-23 08:28 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            self.unassign_agent_group(manager, agent, group_name, check_previous=check_previous)
Done in https://github.com/wazuh/qa-system-framework/pull/71/commits/115f8bd3795d583a316bdc9c13a895abecdbc845

2023-08-23 08:28 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +    def unassign_agents_group(self, manager, list_id_agent, group_name, check_previous=True):
Done in https://github.com/wazuh/qa-system-framework/pull/71/commits/115f8bd3795d583a316bdc9c13a895abecdbc845

2023-08-23 08:28 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +    def unassign_agents_group(self, manager, list_id_agent, group_name, check_previous=True):
Done in https://github.com/wazuh/qa-system-framework/pull/71/commits/115f8bd3795d583a316bdc9c13a895abecdbc845

2023-08-23 08:28 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            self.unassign_agent_group(manager, agent, group_name, check_previous=check_previous)
Done in https://github.com/wazuh/qa-system-framework/pull/71/commits/115f8bd3795d583a316bdc9c13a895abecdbc845

2023-08-23 08:28 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +    def unassign_agent_group(self, manager, id_agent, group_name, check_previous=True):
Done in https://github.com/wazuh/qa-system-framework/pull/71/commits/115f8bd3795d583a316bdc9c13a895abecdbc845

2023-08-23 08:28 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +    def unassign_agent_group(self, manager, id_agent, group_name, check_previous=True):
Done in https://github.com/wazuh/qa-system-framework/pull/71/commits/115f8bd3795d583a316bdc9c13a895abecdbc845

2023-08-23 08:28 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        """Function to assign an agent to a group.
Done in https://github.com/wazuh/qa-system-framework/pull/71/commits/115f8bd3795d583a316bdc9c13a895abecdbc845

2023-08-23 08:28 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +    def delete_group(self, manager, group_name, method='cmd', check_previous=True):
Done in https://github.com/wazuh/qa-system-framework/pull/71/commits/115f8bd3795d583a316bdc9c13a895abecdbc845

2023-08-23 08:28 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +    def check_agent_group(self, manager, id_agent, group_name):
Done in https://github.com/wazuh/qa-system-framework/pull/71/commits/115f8bd3795d583a316bdc9c13a895abecdbc845

2023-08-23 08:29 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        """Function to check the existence of an agent in a group.
Done in https://github.com/wazuh/qa-system-framework/pull/71/commits/115f8bd3795d583a316bdc9c13a895abecdbc845

2023-08-23 08:29 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +    def check_group(self, manager, group_name):
Done in https://github.com/wazuh/qa-system-framework/pull/71/commits/115f8bd3795d583a316bdc9c13a895abecdbc845

2023-08-23 08:29 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +    def assign_agents_group(self, manager, list_id_agent, group_name, method='cmd', check_previous=True):
Done in https://github.com/wazuh/qa-system-framework/pull/71/commits/115f8bd3795d583a316bdc9c13a895abecdbc845

2023-08-23 08:29 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +    def assign_agents_group(self, manager, list_id_agent, group_name, method='cmd', check_previous=True):
Done in https://github.com/wazuh/qa-system-framework/pull/71/commits/115f8bd3795d583a316bdc9c13a895abecdbc845

2023-08-23 08:29 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +    def assign_agent_group(self, manager, id_agent, group_name, method='cmd', check_previous=True):
Done in https://github.com/wazuh/qa-system-framework/pull/71/commits/115f8bd3795d583a316bdc9c13a895abecdbc845

2023-08-23 08:29 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +    def assign_agent_group(self, manager, id_agent, group_name, method='cmd', check_previous=True):
Done in https://github.com/wazuh/qa-system-framework/pull/71/commits/115f8bd3795d583a316bdc9c13a895abecdbc845

2023-08-23 08:29 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            check_previous (str): Check if the group exists.
Done in https://github.com/wazuh/qa-system-framework/pull/71/commits/115f8bd3795d583a316bdc9c13a895abecdbc845

2023-08-23 08:29 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        """Function to delete a group.
Done in https://github.com/wazuh/qa-system-framework/pull/71/commits/115f8bd3795d583a316bdc9c13a895abecdbc845

2023-08-23 08:29 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +    def create_group(self, manager, group_name, method='cmd', check_previous=True):
Done in https://github.com/wazuh/qa-system-framework/pull/71/commits/115f8bd3795d583a316bdc9c13a895abecdbc845

2023-08-23 08:29 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        """Function to create a group.
Done in https://github.com/wazuh/qa-system-framework/pull/71/commits/115f8bd3795d583a316bdc9c13a895abecdbc845

2023-08-23 08:29 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +    def check_agent_group(self, manager, id_agent, group_name):
Done in https://github.com/wazuh/qa-system-framework/pull/71/commits/115f8bd3795d583a316bdc9c13a895abecdbc845

2023-08-23 08:29 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        return True if group_name in self.run_command(manager, f"{get_bin_directory_path()}/agent_groups -l")[1] else False
Done in https://github.com/wazuh/qa-system-framework/pull/71/commits/115f8bd3795d583a316bdc9c13a895abecdbc845

2023-08-23 08:29 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        return True if group_name in self.run_command(manager, f"{get_bin_directory_path()}/agent_groups -l")[1] else False
Done in https://github.com/wazuh/qa-system-framework/pull/71/commits/115f8bd3795d583a316bdc9c13a895abecdbc845

2023-08-23 08:29 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        """Function to check the existance of a group.
Done in https://github.com/wazuh/qa-system-framework/pull/71/commits/115f8bd3795d583a316bdc9c13a895abecdbc845

2023-08-23 08:29 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +
Done in https://github.com/wazuh/qa-system-framework/pull/71/commits/115f8bd3795d583a316bdc9c13a895abecdbc845

2023-11-15 15:45 UTC, Rebits requested changes
Great job. Some minor changes are requied

2023-11-15 15:45 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +    def get_agents_id(self, manager, agents_list=None):
Why agents_list is None by default?
```suggestion
    def get_agents_id(self, manager, agents_list):
```

2023-11-15 15:45 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        return result_id
Unnecessary API call for each agent, instead, store the result and iterate it

2023-11-15 15:45 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        return group_list
```suggestion

        return group_list
```

2023-11-15 15:45 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            method (str): Method to be used to get information. Defaults to api.
There is no return value in the docstring

2023-11-15 15:45 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        self.logger.info(f'Requesting group list info using {method.upper()}')
```suggestion
        self.logger.info(f"Requesting group list info using {method.upper()}")
```

2023-11-15 15:45 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            endpoint = f'/groups'
```suggestion
            endpoint = '/groups'
```

2023-11-15 15:45 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +                group_list.append(item['name'])
- Avoid generics variable names
- This `WazuhAPI(address=self.get_host_variables(manager)['ip'])` is used around all the class, consider create a method to get the WazuhAPI class of a manager.

```suggestion
            for group in request.send(WazuhAPI(address=self.get_host_variables(manager)['ip'])).data['affected_items']:
                group_list.append(group['name'])
```

2023-11-15 15:45 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            group_list = self.run_command(manager, f'{get_bin_directory_path()}/agent_groups')
```suggestion
            group_list = self.run_command(manager, f"{get_bin_directory_path()}/agent_groups")
```

2023-11-15 15:45 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            group_name (str): Name of group.
There is no return value in this docstring

2023-11-15 15:45 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +
```suggestion
```

2023-11-15 15:45 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        return True if group_name in self.get_group_list(manager, method) else False
```suggestion
        return group_name in self.get_group_list(manager, method)
```

2023-11-15 15:45 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            method (str): Method to be used to check. Defaults to api.
Missing return in docstring

2023-11-15 15:45 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            endpoint = f'/agents/{self.get_agent_id(agent_name)}/group/{group_name}'
```suggestion
            endpoint = f"/agents/{self.get_agent_id(agent_name)}/group/{group_name}"
```

2023-11-15 15:45 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            self.logger.info(f'{agent_name} is not assigned to {group_name}')
```suggestion
            self.logger.info(f"{agent_name} is not assigned to {group_name}")
```

2023-11-15 15:45 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            if method == 'api':
```suggestion

            elif method == 'api':
```

2023-11-15 15:45 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +                endpoint = f'/groups?groups_list={group_name}'
```suggestion
                endpoint = f"/groups?groups_list={group_name}"
```

2023-11-15 15:45 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        return True if agent_name in self.get_agents_names_in_group(manager, group_name) else False
```suggestion
        return agent_name in self.get_agents_names_in_group(manager, group_name)
```

2023-11-15 15:45 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            return agent_list
Problematic logic
Currently we deploy multiple instances in a common server. All agent from that common server will have the same IP, so this could be problematic.
I sugges to to implement it by using registration name instead

2023-11-15 15:45 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +                endpoint = f'/groups?groups_list={group_name}'
```suggestion
            elif method == 'api':
                endpoint = f'/groups?groups_list={group_name}'
```

2023-11-15 15:45 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            self.pool.map(lambda agent: self.assign_agent_group(manager, agent, group_name, method=method,
Use starmap instead avoiding lambda function to improve readability

2023-11-15 15:45 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +                self.logger.info(f'Assigning agent {agent} from group {group_name} from {manager}')
Duplicated logger. This is already defined in the `assign_agent_group`
This method should include info logger at the start of the method instead.

2023-11-15 15:45 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +                          list_agent_names)
Same as before, use starmap instead

2023-11-15 20:36 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            str: Agent ip (str).
It is the ip of the host, not the name. Usually names are like: for example, the following format: "172.31.11.159"

2023-11-16 11:49 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            if self.get_host_variables(host).get('ip') == agent_ip:
Changed by self.get_host_ansible_ip(host)

2023-11-16 16:01 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            return agent_list
When dealing with internal IPs, this logic performed well. However, an issue arises when using names like "agent1," "agent2," "agent3," or IDs such as "001," "002," "003." These identifiers encompass all resources where a list of agents can be obtained, including Managers. If all entities are consistently referred to as "agents," it can serve as a unified informational resource.

2023-11-16 17:05 UTC, pro-akim commented
Tests: 

<details><summary>Testing</summary>
wh.get_agent_id('agent1')
002

wh.get_agent_name_from_ip('172.31.2.54')
agent1

wh.get_agents_id('manager1', ['agent1','agent3'])
['001', '002']

wh.get_group_list('manager1', method='api')
['default']

wh.get_group_list('manager1', method='cmd')
['default']

wh.get_agents_names_in_group('manager1', 'default')
['agent1', 'agent3', 'agent2']


wh.check_group('manager1', 'default', method='api')
True

wh.check_group('manager1', 'default', method='cmd')
True

wh.check_agent_group('manager1', 'agent1', 'default')
True

wh.check_agent_group('manager1', 'agent1', 'grupo10')
False

wh.create_group('manager1', 'grupotest1', method='api', check_group=True)
wh.check_group('manager1', 'grupotest1')
True

wh.create_group('manager1', 'grupotest2', method='api', check_group=True)
2023-11-16 15:51:13,647 - INFO - grupotest1 already exists [WazuhEnvironmentHandler create_group:968]
wh.check_group('manager1', 'grupotest1')
True

wh.create_group('manager1', 'grupotest3', method='api', check_group=False)
wh.check_group('manager1', 'grupotest3')
True

wh.create_group('manager1', 'grupotest2', method='api', check_group=True)
wh.check_group('manager1', 'grupotest2')
True

wh.delete_group('manager1', 'grupotest4', method='cmd', check_group=True)
wh.check_group('manager1', 'grupotest4')
False

wh.delete_group('manager1', 'grupotest4', method='cmd', check_group=True)
2023-11-16 15:54:16,587 - INFO - grupotest4 does not exists [WazuhEnvironmentHandler delete_group:987]
wh.check_group('manager1', 'grupotest4')
False

wh.delete_group('manager1', 'grupotest2', method='folder', check_group=True)
wh.check_group('manager1', 'grupotest2')
False

wh.delete_group('manager1', 'grupotest2', method='folder', check_group=True)
2023-11-16 15:56:46,886 - INFO - grupotest2 does not exists [WazuhEnvironmentHandler delete_group:987]
wh.check_group('manager1', 'grupotest2')
False

wh.assign_agent_group('manager1', 'agent1', group_name='grupotest20', check_group=True)
wh.check_agent_group('manager1', 'agent1', 'grupotest20')
True

wh.assign_agent_group('manager1', 'agent2', group_name='grupotest20', check_group=True)
wh.check_agent_group('manager1', 'agent2', 'grupotest20')
True

wh.assign_agent_group('manager1', 'agent3', group_name='grupotest20', check_group=True)
2023-11-16 15:58:54,915 - INFO - agent3 is already assigned to grupotest20 [WazuhEnvironmentHandler assign_agent_group:1013]
wh.check_agent_group('manager1', 'agent3', 'default')
True

wh.assign_agents_group('manager1', ['agent1', 'agent2'], group_name='grupotest10', method='api', check_group=True)
wh.check_agent_group('manager1', 'agent1', 'grupotest10')
wh.check_agent_group('manager1', 'agent2', 'grupotest10')
True
True

wh.assign_agents_group('manager1', ['agent1', 'agent2'], group_name='grupotest10', method='api', check_group=True)
wh.check_agent_group('manager1', 'agent1', 'grupotest10')
wh.check_agent_group('manager1', 'agent2', 'grupotest10')
2023-11-16 16:02:47,126 - INFO - agent2 is already assigned to grupotest10 [WazuhEnvironmentHandler assign_agent_group:999]
2023-11-16 16:02:47,128 - INFO - agent1 is already assigned to grupotest10 [WazuhEnvironmentHandler assign_agent_group:999]
True
True

wh.unassign_agent_group('manager1', 'agent1', group_name='default', check_group=True)
wh.check_agent_group('manager1', 'agent1', 'default')
False

wh.unassign_agents_group('manager1', ['agent1', 'agent2'], group_name='grupotest10', check_group=True)  
wh.check_agent_group('manager1', 'agent1', 'grupotest10')
wh.check_agent_group('manager1', 'agent2', 'grupotest10')
2023-11-16 16:05:20,490 - INFO - Removing agent agent2 from group grupotest10 using API [WazuhEnvironmentHandler unassign_agent_group:1039]
2023-11-16 16:05:20,490 - INFO - Removing agent agent1 from group grupotest10 using API [WazuhEnvironmentHandler unassign_agent_group:1039]
False
False

wh.assign_agents_group('manager1', ['agent1', 'agent2'], group_name='grupotest10', method='api', check_group=True, parallel=False)
wh.check_agent_group('manager1', 'agent1', 'grupotest10')
wh.check_agent_group('manager1', 'agent2', 'grupotest10')
True
True

wh.unassign_agents_group('manager1', ['agent1', 'agent2'], group_name='grupotest10', check_group=True, parallel=False)  
wh.check_agent_group('manager1', 'agent1', 'grupotest1')
wh.check_agent_group('manager1', 'agent2', 'grupotest1')
2023-11-16 16:06:20,490 - INFO - Removing agent agent2 from group grupotest10 using API [WazuhEnvironmentHandler unassign_agent_group:1039]
2023-11-16 16:06:20,490 - INFO - Removing agent agent1 from group grupotest10 using API [WazuhEnvironmentHandler unassign_agent_group:1039]
False
False

</details>

2023-11-16 17:20 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +                          list_agent_names)
Done in https://github.com/wazuh/qa-system-framework/pull/71/commits/56b13fd995d0c2ff5bf72f28f07e8115eb52d246

2023-11-16 17:20 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +                self.logger.info(f'Assigning agent {agent} from group {group_name} from {manager}')
Done in https://github.com/wazuh/qa-system-framework/pull/71/commits/56b13fd995d0c2ff5bf72f28f07e8115eb52d246

2023-11-16 17:20 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            self.pool.map(lambda agent: self.assign_agent_group(manager, agent, group_name, method=method,
Done in https://github.com/wazuh/qa-system-framework/pull/71/commits/56b13fd995d0c2ff5bf72f28f07e8115eb52d246

2023-11-16 17:20 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +                endpoint = f'/groups?groups_list={group_name}'
Done in https://github.com/wazuh/qa-system-framework/pull/71/commits/56b13fd995d0c2ff5bf72f28f07e8115eb52d246

2023-11-16 17:20 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            return agent_list
Done in https://github.com/wazuh/qa-system-framework/pull/71/commits/56b13fd995d0c2ff5bf72f28f07e8115eb52d246

2023-11-16 17:20 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        return True if agent_name in self.get_agents_names_in_group(manager, group_name) else False
Done in https://github.com/wazuh/qa-system-framework/pull/71/commits/56b13fd995d0c2ff5bf72f28f07e8115eb52d246

2023-11-16 17:20 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +                endpoint = f'/groups?groups_list={group_name}'
Done in https://github.com/wazuh/qa-system-framework/pull/71/commits/56b13fd995d0c2ff5bf72f28f07e8115eb52d246

2023-11-16 17:20 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            if method == 'api':
Done in https://github.com/wazuh/qa-system-framework/pull/71/commits/56b13fd995d0c2ff5bf72f28f07e8115eb52d246

2023-11-16 17:20 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            self.logger.info(f'{agent_name} is not assigned to {group_name}')
Done in https://github.com/wazuh/qa-system-framework/pull/71/commits/56b13fd995d0c2ff5bf72f28f07e8115eb52d246

2023-11-16 17:21 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            endpoint = f'/agents/{self.get_agent_id(agent_name)}/group/{group_name}'
Done in https://github.com/wazuh/qa-system-framework/pull/71/commits/56b13fd995d0c2ff5bf72f28f07e8115eb52d246

2023-11-16 17:21 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            method (str): Method to be used to check. Defaults to api.
Done in https://github.com/wazuh/qa-system-framework/pull/71/commits/56b13fd995d0c2ff5bf72f28f07e8115eb52d246

2023-11-16 17:21 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        return True if group_name in self.get_group_list(manager, method) else False
Done in https://github.com/wazuh/qa-system-framework/pull/71/commits/56b13fd995d0c2ff5bf72f28f07e8115eb52d246

2023-11-16 17:21 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +
Done in https://github.com/wazuh/qa-system-framework/pull/71/commits/56b13fd995d0c2ff5bf72f28f07e8115eb52d246

2023-11-16 17:21 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            group_name (str): Name of group.
Done in https://github.com/wazuh/qa-system-framework/pull/71/commits/56b13fd995d0c2ff5bf72f28f07e8115eb52d246

2023-11-16 17:21 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            group_list = self.run_command(manager, f'{get_bin_directory_path()}/agent_groups')
Done in https://github.com/wazuh/qa-system-framework/pull/71/commits/56b13fd995d0c2ff5bf72f28f07e8115eb52d246

2023-11-16 17:21 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +                group_list.append(item['name'])
Done in https://github.com/wazuh/qa-system-framework/pull/71/commits/56b13fd995d0c2ff5bf72f28f07e8115eb52d246

2023-11-16 17:21 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            endpoint = f'/groups'
Done in https://github.com/wazuh/qa-system-framework/pull/71/commits/56b13fd995d0c2ff5bf72f28f07e8115eb52d246

2023-11-16 17:21 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        self.logger.info(f'Requesting group list info using {method.upper()}')
Done in https://github.com/wazuh/qa-system-framework/pull/71/commits/56b13fd995d0c2ff5bf72f28f07e8115eb52d246

2023-11-16 17:21 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            method (str): Method to be used to get information. Defaults to api.
Done in https://github.com/wazuh/qa-system-framework/pull/71/commits/56b13fd995d0c2ff5bf72f28f07e8115eb52d246

2023-11-16 17:21 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        return group_list
Done in https://github.com/wazuh/qa-system-framework/pull/71/commits/56b13fd995d0c2ff5bf72f28f07e8115eb52d246

2023-11-16 17:21 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        return result_id
Done in https://github.com/wazuh/qa-system-framework/pull/71/commits/56b13fd995d0c2ff5bf72f28f07e8115eb52d246

2023-11-16 17:21 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +    def get_agents_id(self, manager, agents_list=None):
Done in https://github.com/wazuh/qa-system-framework/pull/71/commits/56b13fd995d0c2ff5bf72f28f07e8115eb52d246

2023-11-16 17:21 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            if self.get_host_variables(host).get('ip') == agent_ip:
Done in https://github.com/wazuh/qa-system-framework/pull/71/commits/56b13fd995d0c2ff5bf72f28f07e8115eb52d246

2023-11-16 17:21 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            str: Agent ip (str).
Done in https://github.com/wazuh/qa-system-framework/pull/71/commits/56b13fd995d0c2ff5bf72f28f07e8115eb52d246

2023-11-16 17:21 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +    return os.path.join(installation_path, 'bin')
Done in https://github.com/wazuh/qa-system-framework/pull/71/commits/56b13fd995d0c2ff5bf72f28f07e8115eb52d246

2023-11-22 09:50 UTC, Rebits requested changes

2023-11-22 09:50 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +                return self.get_host_variables(host).get('inventory_hostname_short')
Some feedback regarding this method:
- This method handles only inventory data, so it should be placed in HostManager
- This method should be generic for all kinds of instances of the environment, so, variable and method naming should be adjusted

2023-11-22 09:50 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            """
- Docstring format does not fit the repository standard
- Docstring is nos descriptive enough. It should contain how the ids are gathered.
- Manager variable should be optional, using master node as default. 
- Manager parameter docstring documentation should include a minor comment regarding for which this data is used, due to it is not intuitive

2023-11-22 09:50 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            endpoint = f"/agents"
```suggestion
            agent_endpoint = "/agents"
```

2023-11-22 09:50 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            return result_id
Same problem as previously reported. IP is not the best field to get an agent data. Use agent's name instead (the used for enrollment) instead. This could require to obtain the enrollment name used for each agent in a separate method

2023-11-22 09:50 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            return agent_list
We should use enrollment name of the agent instead.
In addition we should consider getting this information using another methods (control group or client keys)

2023-11-22 14:38 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            return result_id
After some conversation, core part of this function was moved to API method.
Testing it in infrastructure where all the machines had different OS (different IP). This method worked OK. However, when more than 1 macOS machine was present, the method failed due to repetition of IPs in different agents

2023-11-22 14:39 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            endpoint = f"/agents"
Done in  https://github.com/wazuh/qa-system-framework/pull/71/commits/d23920d5a17d3df12d274d08dd2e2887e0c5332b

2023-11-22 14:39 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            """
Done in  https://github.com/wazuh/qa-system-framework/pull/71/commits/d23920d5a17d3df12d274d08dd2e2887e0c5332b

2023-11-22 14:39 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +                return self.get_host_variables(host).get('inventory_hostname_short')
Done in  https://github.com/wazuh/qa-system-framework/pull/71/commits/d23920d5a17d3df12d274d08dd2e2887e0c5332b

2023-11-22 14:39 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +    'darwin': '/Library/Ossec',
Done in  https://github.com/wazuh/qa-system-framework/pull/71/commits/d23920d5a17d3df12d274d08dd2e2887e0c5332b

2023-11-22 15:20 UTC, Rebits approved these changes
LGTM

2023-11-22 15:31 UTC, Rebits approved these changes

2023-11-23 09:34 UTC, merged