Stopping agents ungracefully feature
wazuh/qa-system-framework pull request #72
Opened 2023-06-28 12:46 UTC by pro-akim

| Related Issue | 
| --- |
| #61  |

### Description

This PR includes additional parameters for stop_agent and stop_agents, making possible to stop them ungracefully

### Evidences

Running:
<details>

1. wh.stop_agent("agent1", type='gracefully')

2. wh.stop_agent("agent1", type='ungracefully')

3. wh.stop_agents(["agent1", "agent2"], type='gracefully', parallel=True)

4. wh.stop_agents(["agent1", "agent2"], type='ungracefully', parallel=True)

5. wh.stop_agents(["agent1", "agent2"], type='gracefully', parallel=False)

6. wh.stop_agents(["agent1", "agent2"], type='ungracefully', parallel=False)

</details>

Results:
<details>

1. agent1 stopped gracefully

2. agent1 stopped ungracefully

3. agent1 and agent2 stopped gracefully

4. agent1 and agent2 stopped ungracefully

5. agent1 and agent2 stopped gracefully one by one

6. agent1 and agent2 stopped ungracefully one by one

</details>

2023-07-03 19:19 UTC, BelenValdivia commented
@pro-akim Check the failing unit tests

2023-07-05 08:50 UTC, pro-akim commented
## 05/07/2023

Checks were done before the PR, however, it will be tested one more time when the pipeline is back. It will remain on on-hold status.

2023-07-10 14:48 UTC, BelenValdivia commented
PR checks still failing
![image](https://github.com/wazuh/qa-system-framework/assets/26927338/fed3a239-aa67-4d3d-bb44-6171048ec3b2)

2023-07-11 08:18 UTC, pro-akim commented
Automatically triggered unit tests detect failures in code that was not modified by this issue.
It will be researched.

2023-07-11 13:41 UTC, pro-akim commented
# 11/07/2023
The status code was 403 (certificate problems). 
After a new run, unit tests have passed successfully.

2023-07-11 17:51 UTC, BelenValdivia approved these changes

2023-07-11 18:49 UTC, Rebits requested changes

2023-07-11 18:49 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
>          """
It is better to implement this as a boolean condition instead of a string

2023-07-11 18:49 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        service_name = WAZUH_ANGENT_WINDOWS_SERVICE_NAME if self.is_windows(host) else 'wazuh-agent'
Previous typo. Please fix it in all the iterations
```suggestion
        service_name = WAZUH_AGENT_WINDOWS_SERVICE_NAME if self.is_windows(host) else 'wazuh-agent'
```

2023-07-11 18:49 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +                    self.control_service(host, service_name, 'stopped', become=True)
Hardcoded become, use the become defined in the inventory

2023-07-11 18:49 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +                    self.run_command(host, "pkill -9 wazuh-agent", become=True)
Same

2023-07-11 18:49 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +                    self.logger.debug(f'Agent {host} stopped successfully')
Duplicate. Call it at the end of the method

2023-07-11 18:49 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +                    self.run_command(host, 'taskkill /F /IM wazuh-agent.exe')
Difficult to maintain. Create a method in the HostManager task to ungracefully stop a process and call it in this line using the wazuh-agent as parameter

2023-07-11 18:49 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +    def stop_agents(self, agent_list=None, parallel=True, type='gracefully'):
Same as before. In addition agent_list should not be None by default

2023-07-11 18:49 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +                self.stop_agent(agent, type)
Good catch :ok_hand:

2023-07-11 18:49 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            for agent in manager_list:
```suggestion
            for agent in agent_list:
```

2023-07-13 11:31 UTC, pro-akim commented
### Evidences

Running:
<details>

1. wh.stop_agent("agent1", gracefully=True)

2. wh.stop_agent("agent1", gracefully=False)

3. wh.stop_agents(["agent1", "agent2"], gracefully=True , parallel=True)

4. wh.stop_agents(["agent1", "agent2"], gracefully=False, parallel=True)

5. wh.stop_agents(["agent1", "agent2"], gracefully=True, parallel=False)

6. wh.stop_agents(["agent1", "agent2"], gracefully=False, parallel=False)


</details>

Results:
<details>

1.
```
Wazuh agent_control. List of available agents:
   ID: 000, Name: ip-172-31-14-219.ec2.internal (server), IP: 127.0.0.1, Active/Local
   ID: 001, Name: ip-172-31-4-68, IP: any, Disconnected
   ID: 002, Name: EC2AMAZ-2BV3AJS, IP: any, Active
```

2.
```
Wazuh agent_control. List of available agents:
   ID: 000, Name: ip-172-31-14-219.ec2.internal (server), IP: 127.0.0.1, Active/Local
   ID: 001, Name: ip-172-31-4-68, IP: any, Disconnected
   ID: 002, Name: EC2AMAZ-2BV3AJS, IP: any, Active
```


3.
```
Wazuh agent_control. List of available agents:
   ID: 000, Name: ip-172-31-6-43 (server), IP: 127.0.0.1, Active/Local
   ID: 001, Name: ip-172-31-2-206, IP: any, Disconnected
   ID: 002, Name: EC2AMAZ-2BV3AJS, IP: any, Disconnected
```



4.
```
Wazuh agent_control. List of available agents:
   ID: 000, Name: ip-172-31-6-43 (server), IP: 127.0.0.1, Active/Local
   ID: 001, Name: ip-172-31-2-206, IP: any, Disconnected
   ID: 002, Name: EC2AMAZ-2BV3AJS, IP: any, Disconnected
```


5. 
Stopped one by one
```
Wazuh agent_control. List of available agents:
   ID: 000, Name: ip-172-31-6-43 (server), IP: 127.0.0.1, Active/Local
   ID: 001, Name: ip-172-31-2-206, IP: any, Disconnected
   ID: 002, Name: EC2AMAZ-2BV3AJS, IP: any, Disconnected
```

6.
Stopped one by one
```
Wazuh agent_control. List of available agents:
   ID: 000, Name: ip-172-31-6-43 (server), IP: 127.0.0.1, Active/Local
   ID: 001, Name: ip-172-31-2-206, IP: any, Disconnected
   ID: 002, Name: EC2AMAZ-2BV3AJS, IP: any, Disconnected
```


</details>

Unit tests seem to be ok

2023-07-13 11:33 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +                self.stop_agent(agent, type)
Done in https://github.com/wazuh/qa-system-framework/pull/72/commits/ab390ad2c27a3f205a50472e7c0c3a9dc0368f8c

2023-07-13 11:33 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +    def stop_agents(self, agent_list=None, parallel=True, type='gracefully'):
Done in https://github.com/wazuh/qa-system-framework/pull/72/commits/ab390ad2c27a3f205a50472e7c0c3a9dc0368f8c

2023-07-13 11:33 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +                    self.run_command(host, 'taskkill /F /IM wazuh-agent.exe')
Done in https://github.com/wazuh/qa-system-framework/pull/72/commits/ab390ad2c27a3f205a50472e7c0c3a9dc0368f8c

2023-07-13 11:34 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +                    self.logger.debug(f'Agent {host} stopped successfully')
Done in https://github.com/wazuh/qa-system-framework/pull/72/commits/ab390ad2c27a3f205a50472e7c0c3a9dc0368f8c

2023-07-13 11:34 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +                    self.run_command(host, "pkill -9 wazuh-agent", become=True)
Done in https://github.com/wazuh/qa-system-framework/pull/72/commits/ab390ad2c27a3f205a50472e7c0c3a9dc0368f8c

2023-07-13 11:34 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +                    self.control_service(host, service_name, 'stopped', become=True)
Done in https://github.com/wazuh/qa-system-framework/pull/72/commits/ab390ad2c27a3f205a50472e7c0c3a9dc0368f8c

2023-07-13 11:34 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        service_name = WAZUH_ANGENT_WINDOWS_SERVICE_NAME if self.is_windows(host) else 'wazuh-agent'
Done in https://github.com/wazuh/qa-system-framework/pull/72/commits/ab390ad2c27a3f205a50472e7c0c3a9dc0368f8c

2023-07-17 22:57 UTC, BelenValdivia approved these changes

2023-07-27 09:34 UTC, Rebits requested changes

2023-07-27 09:34 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +
```suggestion
```

2023-07-27 09:34 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            if not gracefully:
```suggestion
            else:
```

2023-07-27 09:34 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            raise ValueError(f'Host {host} is not an Agent')
```suggestion
            raise ValueError(f'Host {host} is not an agent')
```

2023-07-27 09:34 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> -        self.logger.info(f'Agents stopped successfully: {agent_list}')
Why delete the logger?

2023-07-27 09:34 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            for manager in agent_list:
```suggestion
            for manager in manager_list:
```

2023-07-27 09:48 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +                    self.logger.debug(f'Agent {host} stopped successfully')
Mark as resolved. New error reported here https://github.com/wazuh/qa-system-framework/pull/72#discussion_r1276017218

2023-07-27 09:49 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +    def stop_agents(self, agent_list=None, parallel=True, type='gracefully'):
No. Agent list is still initialized as None

2023-07-27 09:53 UTC, Rebits requested changes

2023-07-27 09:53 UTC, Rebits commented on src/wazuh_qa_framework/system/host_manager.py
> +    def stop_ungracefully_process(self, host, process):
Include become logic, similarly to the rest of the methods

2023-07-28 08:29 UTC, pro-akim commented on src/wazuh_qa_framework/system/host_manager.py
> +    def stop_ungracefully_process(self, host, process):
become parameter was not added because self.run_command (method stop_ungracefully_process ends in it) already has it.

2023-07-28 08:45 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> -        self.logger.info(f'Agents stopped successfully: {agent_list}')
it was deleted because self.stop_agent itself has a logging system that will inform when each agent is being stopped

2023-07-28 08:57 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            for manager in agent_list:
Changed on https://github.com/wazuh/qa-system-framework/pull/72/commits/1d588e97672da058370e37243e615872fc0d0799

2023-07-28 08:57 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            raise ValueError(f'Host {host} is not an Agent')
Changed on https://github.com/wazuh/qa-system-framework/pull/72/commits/1d588e97672da058370e37243e615872fc0d0799

2023-07-28 08:58 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            if not gracefully:
Changed on https://github.com/wazuh/qa-system-framework/pull/72/commits/1d588e97672da058370e37243e615872fc0d0799

2023-07-28 08:58 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +
Changed on https://github.com/wazuh/qa-system-framework/pull/72/commits/1d588e97672da058370e37243e615872fc0d0799

2023-07-28 09:13 UTC, pro-akim commented
# Update
Changes done.
Ready to be reviewed.

2023-10-04 17:35 UTC, damarisg requested changes

2023-10-04 17:35 UTC, damarisg commented on src/wazuh_qa_framework/system/host_manager.py
> +    def stop_ungracefully_process(self, host, process):
Some suggestions for the name.

```suggestion
    def process_basic_stop(self, host, process):
```

```suggestion
    def process_simple_stop(self, host, process):
```

2023-10-04 17:35 UTC, damarisg commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +    def stop_agent(self, host, gracefully=True):
Gracefully is not a good name for a variable. Could you think of another name please?
It could be replaced by "basic_cmd", "simple_cmd", "easy_cmd" or "short_cmd".

It is not a mandatory change.

2023-11-15 14:54 UTC, pro-akim commented on src/wazuh_qa_framework/system/host_manager.py
> +    def stop_ungracefully_process(self, host, process):
The `ungracefully` term was taken from issues like https://github.com/wazuh/wazuh/issues/15153#issue-1404640786 where the host connection is crashed or lost. IMHO I wish to keep it because it is a simple word that reflects that situation.

2023-11-15 14:55 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +    def stop_agent(self, host, gracefully=True):
Mentioned https://github.com/wazuh/qa-system-framework/pull/72#discussion_r1394321004

2023-11-16 08:54 UTC, Rebits requested changes
Some minor final changes are requested

2023-11-16 08:54 UTC, Rebits commented on src/wazuh_qa_framework/system/host_manager.py
> +                self.run_command(host, f'pkill -9 {process}')
```suggestion
                self.run_command(host, f'taskkill /F /IM {process}')
            else:
                self.run_command(host, f'pkill -9 {process}')
```
```suggestion
                self.run_command(host, f"taskkill /F /IM {process}")
            else:
                self.run_command(host, f"pkill -9 {process}")
```

2023-11-16 08:54 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            self.logger.info(f'Agent {host} stopped {type}')
```suggestion
            self.logger.info(f"Agent {host} stopped {type}")
```

2023-11-16 08:54 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            self.pool.map(stop_agent_with_type, agent_list)
I suggest to use startmap for consistency with the rest of the methods
```suggestion
            self.pool.starmap(stop_agent_with_type, [(agent, gracefully) for agent in agent_list])
```

2023-11-16 17:51 UTC, pro-akim commented
## Update

Tested and fixed:

### Evidences

Running:
<details>

1. wh.stop_agent("agent1", gracefully=True)

2. wh.stop_agent("agent1", gracefully=False)

3. wh.stop_agents(["agent1", "agent2"], gracefully=True , parallel=True)

4. wh.stop_agents(["agent1", "agent2"], gracefully=False, parallel=True)

5. wh.stop_agents(["agent1", "agent2"], gracefully=True, parallel=False)

6. wh.stop_agents(["agent1", "agent2"], gracefully=False, parallel=False)


</details>

Results:
<details>

1.
```
Wazuh agent_control. List of available agents:
   ID: 000, Name: ip-172-31-9-178 (server), IP: 127.0.0.1, Active/Local
   ID: 001, Name: ip-172-31-3-59, IP: any, Disconnected
   ID: 002, Name: DESKTOP-AQ2R8SM, IP: any, Active

```

2.
```
Wazuh agent_control. List of available agents:
   ID: 000, Name: ip-172-31-9-178 (server), IP: 127.0.0.1, Active/Local
   ID: 001, Name: ip-172-31-3-59, IP: any, Disconnected
   ID: 002, Name: DESKTOP-AQ2R8SM, IP: any, Active
```


3.
```
Wazuh agent_control. List of available agents:
   ID: 000, Name: ip-172-31-9-178 (server), IP: 127.0.0.1, Active/Local
   ID: 001, Name: ip-172-31-3-59, IP: any, Disconnected
   ID: 002, Name: DESKTOP-AQ2R8SM, IP: any, Disconnected
```



4.
```
Wazuh agent_control. List of available agents:
   ID: 000, Name: ip-172-31-9-178 (server), IP: 127.0.0.1, Active/Local
   ID: 001, Name: ip-172-31-3-59, IP: any, Disconnected
   ID: 002, Name: DESKTOP-AQ2R8SM, IP: any, Disconnected
```


5. 
Stopped one by one
```
Wazuh agent_control. List of available agents:
   ID: 000, Name: ip-172-31-9-178 (server), IP: 127.0.0.1, Active/Local
   ID: 001, Name: ip-172-31-3-59, IP: any, Disconnected
   ID: 002, Name: DESKTOP-AQ2R8SM, IP: any, Disconnected
```

6.
Stopped one by one
```
Wazuh agent_control. List of available agents:
   ID: 000, Name: ip-172-31-9-178 (server), IP: 127.0.0.1, Active/Local
   ID: 001, Name: ip-172-31-3-59, IP: any, Disconnected
   ID: 002, Name: DESKTOP-AQ2R8SM, IP: any, Disconnected
```


</details>

Unit tests seem to be ok

2023-11-16 17:52 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            self.pool.map(stop_agent_with_type, agent_list)
Done in https://github.com/wazuh/qa-system-framework/pull/72/commits/1ebf89058de3b4a0eae192c0ede83285e0480140

2023-11-16 17:52 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            self.logger.info(f'Agent {host} stopped {type}')
Done in https://github.com/wazuh/qa-system-framework/pull/72/commits/1ebf89058de3b4a0eae192c0ede83285e0480140

2023-11-16 17:52 UTC, pro-akim commented on src/wazuh_qa_framework/system/host_manager.py
> +                self.run_command(host, f'pkill -9 {process}')
Done in https://github.com/wazuh/qa-system-framework/pull/72/commits/1ebf89058de3b4a0eae192c0ede83285e0480140

2023-11-22 10:34 UTC, Rebits requested changes

2023-11-22 10:34 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +from functools import partial
```suggestion
```

2023-11-22 10:34 UTC, Rebits commented on src/wazuh_qa_framework/system/host_manager.py
> +    def stop_ungracefully_process(self, host, process):
Current approach does not allow set custom become for this operation, due it always use the default Become value for the run_command.

> [!NOTE]
> Become will be deprecated in future versions of the framework. However for consistency it is required to include it in all the methods

2023-11-22 10:54 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +from functools import partial
Done in https://github.com/wazuh/qa-system-framework/pull/72/commits/96dda29fbd72775eddafe2d1a9203961d14b201f

2023-11-22 10:54 UTC, pro-akim commented on src/wazuh_qa_framework/system/host_manager.py
> +    def stop_ungracefully_process(self, host, process):
Done in https://github.com/wazuh/qa-system-framework/pull/72/commits/96dda29fbd72775eddafe2d1a9203961d14b201f

2023-11-22 13:03 UTC, Rebits approved these changes
LGTM

2023-11-22 15:19 UTC, merged