Adding methods for rules and decoders
wazuh/qa-system-framework pull request #73
Opened 2023-06-30 11:36 UTC by pro-akim

| Related Issue | 
| --- |
| #66  |

### Description

This PR includes new methods for adding and replacing rules and decoders.

### Evidences

Running:
<details>
1. wh.change_decoders('manager1', '/home/akim/Desktop/decoder_total.xml')

2. wh.change_rules('manager1', '/home/akim/Desktop/rules_total.xml')

3. wh.add_decoder('manager1', '/home/akim/Desktop/decoder.xml', '/var/ossec/etc/decoders/local_decoder.xml')

4. wh.add_rule('manager1', '/home/akim/Desktop/rule.xml', '/var/ossec/etc/rules/local_rules.xml')

</details>

Results:
<details>
1. Changed '/var/ossec/etc/decoders/local_decoder.xml' by '/home/akim/Desktop/decoder.xml' content.

2. Changed '/var/ossec/etc/rules/local_rules.xml' by '/home/akim/Desktop/rules_total.xml' content.

3. Adding a decoder from '/home/akim/Desktop/decoder.xml' to '/var/ossec/etc/decoders/local_decoder.xml' 

4. Adding a rule from '/home/akim/Desktop/rule.xml' to '/var/ossec/etc/rules/local_rules.xml'

</details>

2023-07-03 16:28 UTC, roronoasins commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        """Change local_rules for a new ruleset
```suggestion
        """Change local_rules for a new ruleset.
```
> I would change the `local_rules` references by its relative path within `/var/ossec` for all the changes

2023-07-03 16:30 UTC, roronoasins commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        self.logger.info(message=f'Changing local_rules.xml to {file_path}')
```suggestion
        self.logger.info(message=f"Changing local_rules.xml to {file_path}")
```

2023-07-03 16:34 UTC, roronoasins commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        self.modify_file_content(host, '/var/ossec/etc/rules/local_rules.xml', new_rules, become=True)
We can use the `get_local_decoders_file_path` from `global_variables.path.config_path`

2023-07-03 16:39 UTC, roronoasins commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +    def change_rules(self, host, file_path):
Should we add another `file_path` so we can change another rule file? because we can have more custom rules files

2023-07-03 16:42 UTC, roronoasins commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            file_path (str): Path of file that will replace local_rules_xml
```suggestion
            file_path (str): The filepath that contains the new rules
```

2023-07-03 16:43 UTC, roronoasins commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        """Add a rule to a rule-set
```suggestion
        """Add new rules to the provided rules file path.
```

2023-07-03 16:45 UTC, roronoasins commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            rule_path (str): Path of file with rules
```suggestion
        """Add new rules to the provided rules file path.

        Args:
            host (str): Host name
            file_path (str): Path of the file that contains the rules that will be added to rules_path
            rule_path (str): Path of the file where the rules will be added
```

2023-07-03 16:47 UTC, roronoasins commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +    def change_decoders(self, host, file_path):
Same https://github.com/wazuh/qa-system-framework/pull/73#discussion_r1251101572 but in this cases for decoders

2023-07-03 16:48 UTC, roronoasins commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            decoder_path (str): Path of file with decoders
Same https://github.com/wazuh/qa-system-framework/pull/73#discussion_r1251108940 but for decoders

2023-07-03 16:50 UTC, roronoasins commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +                    final_rules = current_rules[:index_rule] + '</rule>' + "\n" +  new_rule + '</group>'
```suggestion
                    final_rules = current_rules[:index_rule] + '</rule>\n' +  new_rule + '</group>'
```
> Not a f-string and can be merged

2023-07-04 12:42 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +    def change_rules(self, host, file_path):
Considering the idea that it can be useful to change another rules, it has been modified

2023-07-04 14:08 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            decoder_path (str): Path of file with decoders
Fixes done in https://github.com/wazuh/qa-system-framework/pull/73/commits/dac8a05b3ebb39f5c518ad993058688406a31ecc

2023-07-04 14:08 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +    def change_decoders(self, host, file_path):
Fixes done in https://github.com/wazuh/qa-system-framework/pull/73/commits/dac8a05b3ebb39f5c518ad993058688406a31ecc

2023-07-04 14:08 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            file_path (str): Path of file that will replace local_rules_xml
Fixes done in https://github.com/wazuh/qa-system-framework/pull/73/commits/dac8a05b3ebb39f5c518ad993058688406a31ecc

2023-07-04 14:08 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +    def change_rules(self, host, file_path):
Fixes done in https://github.com/wazuh/qa-system-framework/pull/73/commits/dac8a05b3ebb39f5c518ad993058688406a31ecc

2023-07-04 14:08 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        self.logger.info(message=f'Changing local_rules.xml to {file_path}')
Fixes done in https://github.com/wazuh/qa-system-framework/pull/73/commits/dac8a05b3ebb39f5c518ad993058688406a31ecc

2023-07-04 14:08 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        """Change local_rules for a new ruleset
Fixes done in https://github.com/wazuh/qa-system-framework/pull/73/commits/dac8a05b3ebb39f5c518ad993058688406a31ecc

2023-07-06 10:31 UTC, roronoasins commented
GJ! LGTM

2023-07-06 11:56 UTC, pro-akim commented
## 06/07/2023 
Small changes done around format of f'string use

2023-07-11 19:24 UTC, Rebits requested changes

2023-07-11 19:24 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +    def change_rules(self, host, file_path, rule_path):
Method is not usable. The parameters should be `rule_filename`.  The method should handle the path depending of the host.

2023-07-11 19:24 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +    def change_rules(self, host, file_path, rule_path):
`file_path` is not a precise name. Maybe new_rules_files it could be better. In addition, why use a filepath instead of the rules in a string?

2023-07-11 19:24 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        self.modify_file_content(host, rule_path, new_rules, become=True)
Hardcoded become. Change it regarding the provided inventory

2023-07-11 19:24 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        self.modify_file_content(host, rule_path, new_rules, become=True)
No logger for operation confirmation

2023-07-11 19:24 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +    def add_rule(self, host, file_path, rules_path):
Discrepancies with previous method. Rename to `add_rules` instead

2023-07-11 19:24 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +    def add_rule(self, host, file_path, rules_path):
Same as before, `rules_path` should be `rule_filename` instead

2023-07-11 19:24 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            rules_path (str): Path of the file where the rules will be added
```suggestion
        file_path (str): Path of the source rules file.
        rules_path (str): Path of the destination rules file.
```

2023-07-11 19:24 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        """Change local_decoder for new decoders.
Not precise docstring. This method applies to any decoder file

2023-07-11 19:24 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +    def change_decoders(self, host, file_path, decoder_path):
Same as before. Replace method name with `create_decoders`.

2023-07-11 19:24 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +    def change_decoders(self, host, file_path, decoder_path):
Same as before. Why not using a string with the new decoders?

2023-07-11 19:24 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +    def change_decoders(self, host, file_path, decoder_path):
Same as before. Replace `decoder_path` with `decoder_filename`

2023-07-11 19:24 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            decoder_path (str): Path of the file that contains the old decoders to be changed
```suggestion
        file_path (str): Path of the source decoders file.
        rules_path (str): Path of the destination decoders file.
```

2023-07-11 19:24 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        self.modify_file_content(host, {decoder_path}, new_decoders, become=True)
```suggestion
        self.modify_file_content(host, decoder_path, new_decoders, become=True)
```

2023-07-11 19:24 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        self.modify_file_content(host, {decoder_path}, new_decoders, become=True)
Hardcoded become

2023-07-11 19:24 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        """Add new decoders to the provided decoer file path.
```suggestion
        """Add new decoders to the provided decoder file path.
```

2023-07-11 19:24 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +    def add_decoder(self, host, file_path, decoders_path):
Same as previous methods

2023-07-11 19:24 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            decoders_path (str): Path of the file where the decoders will be added
```suggestion
        file_path (str): Path of the source decoders file.
        rules_path (str): Path of the destination decoders file.
```

2023-07-11 19:24 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        current_decoders = self.get_file_content(host, decoders_path, become=True, ignore_errors=False)
Hardcoded become

2023-07-11 19:24 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        if index_decoder != -1:
No else clause. It will fail if there is no decoders in the file

2023-07-11 19:24 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +                    final_decoders = current_decoders[:index_decoder] + '</decoder>\n' + new_decoder
Respect indentation

2023-07-11 19:24 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        self.modify_file_content(host, decoders_path, final_decoders, become=True, ignore_errors=True)
Hardcoded become

2023-07-12 17:53 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +    def change_rules(self, host, file_path, rule_path):
String was changed by file because of the usual decoder structure.

2023-07-12 17:58 UTC, pro-akim commented
# 12/07/2023 Update
All changes were done. 
Add and Change decoders were changed by create decoders
Same for rules.

2023-07-12 18:02 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        service_name = WAZUH_ANGENT_WINDOWS_SERVICE_NAME if self.is_windows(host) else 'wazuh-agent'
Done in https://github.com/wazuh/qa-system-framework/pull/73/commits/f37fed0d0561cc71b746d80b3b5fe98b5e704c2e

2023-07-12 18:02 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +    def change_rules(self, host, file_path, rule_path):
Done in https://github.com/wazuh/qa-system-framework/pull/73/commits/f37fed0d0561cc71b746d80b3b5fe98b5e704c2e

2023-07-12 18:02 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        """Change local_rules for a new ruleset.
Done in https://github.com/wazuh/qa-system-framework/pull/73/commits/f37fed0d0561cc71b746d80b3b5fe98b5e704c2e

2023-07-12 18:02 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +    def change_rules(self, host, file_path, rule_path):
Done in https://github.com/wazuh/qa-system-framework/pull/73/commits/f37fed0d0561cc71b746d80b3b5fe98b5e704c2e

2023-07-12 18:02 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            decoders_path (str): Path of the file where the decoders will be added
Done in https://github.com/wazuh/qa-system-framework/pull/73/commits/f37fed0d0561cc71b746d80b3b5fe98b5e704c2e

2023-07-12 18:02 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        if index_decoder != -1:
Done in https://github.com/wazuh/qa-system-framework/pull/73/commits/f37fed0d0561cc71b746d80b3b5fe98b5e704c2e

2023-07-12 18:02 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +                    final_decoders = current_decoders[:index_decoder] + '</decoder>\n' + new_decoder
Done in https://github.com/wazuh/qa-system-framework/pull/73/commits/f37fed0d0561cc71b746d80b3b5fe98b5e704c2e

2023-07-12 18:03 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        self.modify_file_content(host, decoders_path, final_decoders, become=True, ignore_errors=True)
Changed in https://github.com/wazuh/qa-system-framework/pull/73/commits/339d935858b5ca2b5866da465bc2893aadc67131

2023-07-12 18:03 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +        current_decoders = self.get_file_content(host, decoders_path, become=True, ignore_errors=False)
Changed in https://github.com/wazuh/qa-system-framework/pull/73/commits/339d935858b5ca2b5866da465bc2893aadc67131

2023-07-27 11:00 UTC, Rebits requested changes

2023-07-27 11:00 UTC, Rebits commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +                self.logger.info(message=f'Changing {decoder_filename} to {new_decoder_filename}')
Same as before

2023-08-01 10:01 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +                self.logger.info(message=f'Changing {rules_filename} to {new_rule_filename}')
With the new flow (adding creation of new file), it will make sense to keep it in this position

2023-08-01 10:03 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +                    self.logger.info(message=f'Adding rule from {new_rule_filename} to {rules_filename}')
It is because <rule></rule> should go inside <group></group> and follow the previous (preexisting) rule.

2023-08-01 13:27 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +                self.logger.info(message=f'Changing {decoder_filename} to {new_decoder_filename}')
Fixed in https://github.com/wazuh/qa-system-framework/pull/73/commits/30e6c21bf79b7df863b6edfd92060d4689b1be92

2023-08-01 13:27 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            self.logger.info(message=f'Rules succefully updated')
Fixed in https://github.com/wazuh/qa-system-framework/pull/73/commits/30e6c21bf79b7df863b6edfd92060d4689b1be92

2023-08-01 13:27 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            overwrite (bool): replace the rules file True, add rules to rules file, False. Defaults to True.
Fixed in https://github.com/wazuh/qa-system-framework/pull/73/commits/30e6c21bf79b7df863b6edfd92060d4689b1be92

2023-08-01 13:27 UTC, pro-akim commented on src/wazuh_qa_framework/system/wazuh_handler.py
> +            self.logger.error(message=f'The file {new_rule_filename} does not exist.')
Fixed in https://github.com/wazuh/qa-system-framework/pull/73/commits/30e6c21bf79b7df863b6edfd92060d4689b1be92

2023-08-01 13:38 UTC, pro-akim commented
# Update
Fixes done after review.
Linting detects multiple spaces after operators in line 900. No multiple spaces were found.

2023-08-30 19:55 UTC, BelenValdivia approved these changes

2023-09-06 08:31 UTC, merged